Repository e2b-dev/infra, pull requests merged in 2024-04, with the labels that each got.

#124 Fix missing MMDS in some sandboxes
  packages/env-instance-task-driver/internal/instance/fc.go
  packages/env-instance-task-driver/internal/instance/mock_instance.go
Labels: bug

#91 Add API endpoint for retrieving sandbox logs
  go.work.sum
  main.tf
  packages/api/go.mod
  packages/api/go.sum
  packages/api/internal/api/api.gen.go
  packages/api/internal/api/spec.gen.go
  packages/api/internal/api/types.gen.go
  packages/api/internal/handlers/sandbox_kill.go
  packages/api/internal/handlers/sandbox_logs.go
  packages/api/internal/handlers/sandbox_refresh.go
  packages/api/internal/handlers/store.go
  packages/api/internal/utils/split.go
  packages/buckets/main.tf
  packages/buckets/outputs.tf
  packages/nomad/api.hcl
  packages/nomad/logs-collector.hcl
  packages/nomad/loki.hcl
  packages/nomad/main.tf
  packages/nomad/otel-collector.hcl
  packages/nomad/variables.tf
  spec/openapi.yml
  variables.tf
Labels: feature

#129 Fix process output scan buffer initialization and resizing
  packages/envd/internal/process/service.go
Labels: bug

#132 Improve huge pages handling in client start script
  packages/cluster/scripts/start-client.sh
Labels: improvement

#140 Remove unnecessary cleanup method and fix cleanup order
  packages/orchestrator/internal/server/sandboxes.go
Labels: bug, improvement

#133 Update and simplify Nomad jobs
  packages/cluster-disk-image/main.pkr.hcl
  packages/nomad/api.hcl
  packages/nomad/client-proxy.hcl
  packages/nomad/docker-reverse-proxy.hcl
  packages/nomad/logs-collector.hcl
  packages/nomad/loki.hcl
  packages/nomad/orchestrator.hcl
  packages/nomad/otel-collector.hcl
  packages/nomad/session-proxy.hcl
Labels: improvement

#141 Remove unnecessary cleanup method and fix cleanup order #140
  packages/nomad/api.hcl
  packages/nomad/client-proxy.hcl
  packages/nomad/docker-reverse-proxy.hcl
  packages/nomad/logs-collector.hcl
  packages/nomad/loki.hcl
  packages/nomad/orchestrator.hcl
  packages/nomad/otel-collector.hcl
  packages/nomad/session-proxy.hcl
Labels: improvement

#143 Add default consul agent token
  packages/cluster/scripts/run-consul.sh
  packages/cluster/scripts/start-client.sh
Labels: improvement

#145 Decrease max unavailable servers to 1
  packages/cluster/server/main.tf
  packages/cluster/server/variables.tf
Labels: improvement

#146 Set limits for orchestrator based on the machine
  .terraform.lock.hcl
  main.tf
  packages/api/main.tf
  packages/nomad/main.tf
  packages/nomad/orchestrator.hcl
  packages/nomad/variables.tf
  packages/shared/pkg/telemetry/otel.go
Labels: improvement

#148 Fix UFFD and Firecracker killing in orchestrator
  packages/orchestrator/Makefile
  packages/orchestrator/internal/sandbox/fc.go
  packages/orchestrator/internal/sandbox/files.go
  packages/orchestrator/internal/sandbox/mock_instance.go
  packages/orchestrator/internal/sandbox/process.go
  packages/orchestrator/internal/sandbox/sandbox.go
  packages/orchestrator/internal/sandbox/slot.go
  packages/orchestrator/internal/sandbox/uffd.go
  packages/orchestrator/internal/server/main.go
  packages/orchestrator/internal/server/sandboxes.go
Labels: bug, improvement

#151 Add swap and adjust OOM handling in sandbox
  packages/template-manager/internal/build/provision.sh
Labels: bug, improvement

#152 Add logs and metrics from proxies
  packages/nomad/client-proxy.hcl
  packages/nomad/otel-collector.hcl
  packages/nomad/session-proxy.hcl
Labels: improvement
