Repository e2b-dev/infra, pull requests merged in 2024-08, with the labels that each got.

#169 Handle multiple teams for a user and allow specifying a team when building a new template
  packages/api/internal/api/api.gen.go
  packages/api/internal/api/spec.gen.go
  packages/api/internal/api/types.gen.go
  packages/api/internal/cache/templates/cache.go
  packages/api/internal/handlers/auth.go
  packages/api/internal/handlers/store.go
  packages/api/internal/handlers/teams.go
  packages/api/internal/handlers/template_build_logs.go
  packages/api/internal/handlers/template_delete.go
  packages/api/internal/handlers/template_get.go
  packages/api/internal/handlers/template_request_build.go
  packages/api/internal/handlers/template_start_build.go
  packages/nomad/main.tf
  packages/shared/migrations/20000101000000.sql
  packages/shared/migrations/20240728094137.sql
  packages/shared/migrations/atlas.sum
  packages/shared/pkg/db/envs.go
  packages/shared/pkg/db/users.go
  packages/shared/pkg/models/migrate/schema.go
  packages/shared/pkg/models/mutation.go
  packages/shared/pkg/models/runtime.go
  packages/shared/pkg/models/team_create.go
  packages/shared/pkg/models/team_update.go
  packages/shared/pkg/models/user_create.go
  packages/shared/pkg/models/user_update.go
  packages/shared/pkg/models/usersteams.go
  packages/shared/pkg/models/usersteams/usersteams.go
  packages/shared/pkg/models/usersteams/where.go
  packages/shared/pkg/models/usersteams_create.go
  packages/shared/pkg/models/usersteams_update.go
  packages/shared/pkg/schema/users_teams.go
  spec/openapi.yml
Labels: bug, improvement

#168 Add information about how long sandbox will run when listing sandboxes
  packages/api/internal/api/spec.gen.go
  packages/api/internal/api/types.gen.go
  packages/api/internal/cache/instance/instance.go
  packages/api/internal/cache/instance/operations.go
  packages/api/internal/cache/instance/sync.go
  packages/api/internal/handlers/sandbox_create.go
  packages/api/internal/handlers/sandbox_refresh.go
  packages/api/internal/handlers/sandbox_timeout.go
  packages/api/internal/handlers/sandboxes_list.go
  packages/api/internal/orchestrator/create_instance.go
  packages/api/internal/orchestrator/list_instances.go
  packages/api/internal/orchestrator/update_instance.go
  packages/orchestrator/internal/sandbox/mock_instance.go
  packages/orchestrator/internal/sandbox/sandbox.go
  packages/orchestrator/internal/server/sandboxes.go
  packages/orchestrator/orchestrator.proto
  packages/shared/pkg/grpc/orchestrator/orchestrator.pb.go
  packages/shared/pkg/grpc/orchestrator/orchestrator_grpc.pb.go
  spec/openapi.yml
Labels: feature

#172 Allow to shorten sandbox duration
  packages/api/internal/cache/instance/sync.go
  packages/api/internal/handlers/sandbox_refresh.go
  packages/api/internal/handlers/sandbox_timeout.go
Labels: bug

#173 Return paths from envd filesystem operations
  Makefile
  packages/envd/internal/api/api.gen.go
  packages/envd/internal/api/upload.go
  packages/envd/internal/services/filesystem/dir.go
  packages/envd/internal/services/filesystem/move.go
  packages/envd/internal/services/spec/filesystem/filesystem.pb.go
  packages/envd/internal/services/spec/process/process.pb.go
  packages/envd/spec/envd.yaml
  packages/envd/spec/filesystem/filesystem.proto
Labels: improvement

#175 chore: update rootfs.go
  packages/template-manager/internal/build/rootfs.go
Labels: docs

#177 Add possibility to setup env vars on sbx create
  packages/api/internal/api/spec.gen.go
  packages/api/internal/api/types.gen.go
  packages/api/internal/handlers/sandbox_create.go
  packages/api/internal/orchestrator/create_instance.go
  packages/envd/internal/api/api.gen.go
  packages/envd/internal/api/envs.go
  packages/envd/internal/api/init.go
  packages/envd/internal/api/store.go
  packages/envd/internal/services/process/handler/handler.go
  packages/envd/internal/services/process/service.go
  packages/envd/internal/services/process/start.go
  packages/envd/internal/utils/map.go
  packages/envd/main.go
  packages/envd/spec/envd.yaml
  packages/orchestrator/internal/sandbox/sandbox.go
  packages/orchestrator/internal/server/sandboxes.go
  packages/orchestrator/orchestrator.proto
  packages/shared/pkg/grpc/orchestrator/orchestrator.pb.go
  packages/shared/pkg/grpc/orchestrator/orchestrator_grpc.pb.go
  spec/openapi.yml
Labels: feature

#180 Process with PTY - start only once
  packages/envd/internal/services/process/handler/handler.go
Labels: bug

#171 Move UFFD handling to orchestrator
  .vscode/extensions.json
  .vscode/launch.json
  go.work.sum
  packages/nomad/proxies/client.conf
  packages/nomad/proxies/session.conf
  packages/orchestrator/Makefile
  packages/orchestrator/go.mod
  packages/orchestrator/go.sum
  packages/orchestrator/internal/sandbox/cache/mmapfile.go
  packages/orchestrator/internal/sandbox/fc.go
  packages/orchestrator/internal/sandbox/files.go
  packages/orchestrator/internal/sandbox/mock_instance.go
  packages/orchestrator/internal/sandbox/network.go
  packages/orchestrator/internal/sandbox/process.go
  packages/orchestrator/internal/sandbox/sandbox.go
  packages/orchestrator/internal/sandbox/socket.go
  packages/orchestrator/internal/sandbox/uffd.go
  packages/orchestrator/internal/sandbox/uffd/handler.go
  packages/orchestrator/internal/sandbox/uffd/serve.go
  packages/orchestrator/internal/server/main.go
  packages/orchestrator/internal/server/sandboxes.go
  packages/orchestrator/internal/test/main.go
Labels: bug, improvement
