Repository e2b-dev/infra, pull requests merged in 2024-03, with the labels that each got.

#96 Improve clock sync handling in FC
  packages/env-build-task-driver/Makefile
  packages/env-build-task-driver/internal/env/env.go
  packages/env-build-task-driver/internal/env/mock_build.go
  packages/env-build-task-driver/internal/env/provision.sh
  packages/env-build-task-driver/internal/env/rootfs.go
  packages/env-build-task-driver/internal/env/snapshot.go
  packages/env-build-task-driver/internal/handle.go
  packages/env-instance-task-driver/Makefile
  packages/env-instance-task-driver/internal/instance/fc.go
  packages/env-instance-task-driver/internal/instance/instance.go
  packages/env-instance-task-driver/internal/instance/mock_instance.go
  packages/env-instance-task-driver/main.go
  packages/envd/Makefile
  packages/envd/debug.Dockerfile
  packages/envd/go.mod
  packages/envd/internal/clock/service.go
  packages/envd/internal/log/exporter/exporter.go
  packages/envd/internal/process/service.go
  packages/envd/internal/terminal/service.go
  packages/envd/main.go
  packages/shared/pkg/consts/envd.go
Labels: bug

#86 Cleanup kernel building
  go.work.sum
  packages/env-instance-task-driver/go.mod
  packages/env-instance-task-driver/go.sum
  packages/envd/go.mod
  packages/envd/go.sum
  packages/fc-kernels/build.sh
  packages/fc-kernels/kernel_versions.txt
  packages/fc-kernels/upload.sh
  packages/fc-versions/firecracker_versions.txt
  packages/shared/go.mod
  packages/shared/go.sum
  packages/template-delete-task-driver/go.mod
  packages/template-delete-task-driver/go.sum
Labels: improvement

#111 Use consul token for scraping metrics
  packages/nomad/main.tf
  packages/nomad/otel-collector.hcl
Labels: bug

#114 Fix docker login for Windows
  packages/docker-reverse-proxy/internal/auth/validate.go
  packages/docker-reverse-proxy/internal/handlers/login.go
  packages/docker-reverse-proxy/internal/handlers/proxy.go
  packages/docker-reverse-proxy/internal/handlers/token.go
  packages/docker-reverse-proxy/main.go
Labels: bug

#115 Remove old alias
  packages/api/internal/handlers/template_request_build.go
Labels: bug

#116 Fix data races in Nomad driver during sandbox start
  packages/env-instance-task-driver/internal/driver.go
  packages/env-instance-task-driver/internal/handle.go
  packages/env-instance-task-driver/internal/instance/dns.go
  packages/env-instance-task-driver/internal/instance/fc.go
  packages/env-instance-task-driver/internal/instance/files.go
  packages/env-instance-task-driver/internal/instance/instance.go
  packages/env-instance-task-driver/internal/instance/mock_instance.go
  packages/env-instance-task-driver/internal/instance/network.go
  packages/env-instance-task-driver/internal/task.go
  packages/env-instance-task-driver/main.go
  packages/shared/pkg/telemetry/tracing.go
Labels: bug, improvement

#113 Use Nomad stream for getting job allocations
  packages/api/internal/nomad/client.go
  packages/api/internal/nomad/jobs.go
Labels: improvement
