Repository e2b-dev/infra, pull requests merged in 2025-02, with the labels that each got.

#274 Add proxy config to fix a problem with expecting config on incorrect path
  packages/template-manager/internal/build/provision.sh
Labels: bug, improvement

#273 Add a way to delete paused sandboxes
  packages/api/internal/handlers/template_delete.go
  packages/api/internal/template-manager/delete_template.go
  packages/shared/pkg/db/envs.go
  packages/shared/pkg/grpc/template-manager/template-manager.pb.go
  packages/shared/pkg/grpc/template-manager/template-manager_grpc.pb.go
  packages/template-manager/internal/server/delete_template.go
  packages/template-manager/internal/template/main.go
  packages/template-manager/internal/template/storage.go
  packages/template-manager/template-manager.proto
Labels: feature

#263 Update snapshot metadata and timestamp on subsequent pauses
  packages/shared/migrations/20250106142106.sql
  packages/shared/pkg/db/snapshot.go
Labels: improvement

#279 Fix clock sync on start of the sandbox
  packages/envd/internal/host/sync.go
Labels: bug

#261 api: implement redis cache lookups for dns when configured
  packages/api/go.mod
  packages/api/go.sum
  packages/api/internal/dns/server.go
  packages/api/internal/handlers/store.go
  packages/api/internal/orchestrator/orchestrator.go
  packages/api/main.go
Labels: improvement

#276 Reimplement client proxy in go
  go.work
  main.tf
  packages/api/internal/orchestrator/orchestrator.go
  packages/client-proxy/.gitignore
  packages/client-proxy/Dockerfile
  packages/client-proxy/Makefile
  packages/client-proxy/go.mod
  packages/client-proxy/go.sum
  packages/client-proxy/main.go
  packages/client-proxy/main.tf
  packages/client-proxy/outputs.tf
  packages/client-proxy/variables.tf
  packages/cluster/network/main.tf
  packages/cluster/scripts/run-consul.sh
  packages/docker-reverse-proxy/outputs.tf
  packages/nomad/api.hcl
  packages/nomad/client-proxy.hcl
  packages/nomad/main.tf
  packages/nomad/variables.tf
  packages/shared/pkg/logging/collector.go
Labels: bug, improvement

#284 minor: build improvement for make targets
  Makefile
Labels: improvement

#283 Correct wait group and add exit with appropriate code
  packages/client-proxy/main.go
Labels: improvement

#281 E2B-1536: move team slug & profile migrations to infra
  packages/shared/migrations/20250205180205.sql
Labels: feature

#271 Use runtime logger timestamp instead of log-collector timestamp in sandbox logs and metrics
  packages/api/internal/handlers/sandbox_logs.go
  packages/api/internal/handlers/sandbox_metrics.go
  packages/nomad/logs-collector.hcl
Labels: bug

#249 Add autoscaling (only up) for client
  .env.template
  Makefile
  main.tf
  packages/cluster/client/main.tf
  packages/cluster/client/variables.tf
  packages/cluster/main.tf
  packages/cluster/variables.tf
  variables.tf
Labels: improvement

#280 List sandboxes with metrics
  packages/api/internal/api/api.gen.go
  packages/api/internal/api/spec.gen.go
  packages/api/internal/api/types.gen.go
  packages/api/internal/handlers/sandbox_metrics.go
  packages/api/internal/handlers/sandboxes_list.go
  packages/nomad/loki.hcl
  packages/orchestrator/internal/sandbox/checks.go
  packages/orchestrator/internal/sandbox/metrics.go
  spec/openapi.yml
Labels: feature

#291 Create Grafana Stack with terraform and plumb relevant data to gcp for telemetry
  .env.template
  .gitignore
  main.tf
  packages/init/main.tf
  packages/init/outputs.tf
  packages/nomad/main.tf
  packages/nomad/otel-collector.hcl
  packages/nomad/variables.tf
  self-host.md
  terraform/grafana/.terraform.lock.hcl
  terraform/grafana/Makefile
  terraform/grafana/README.md
  terraform/grafana/main.tf
  terraform/grafana/variables.tf
Labels: improvement

#299 Fix rootfs blocks order in diffs
  packages/orchestrator/internal/sandbox/block/cache.go
Labels: bug

#304 Client proxy improvements
  packages/client-proxy/main.go
Labels: improvement

#308 Fix log-collector label and timestamp errors
  packages/nomad/logs-collector.hcl
  packages/nomad/loki.hcl
Labels: bug

#314 More lenient Loki config and stop timestamp manipulation
  packages/nomad/logs-collector.hcl
  packages/nomad/loki.hcl
Labels: bug

#315 Revert back to using Loki entry timestamp
  packages/api/internal/handlers/sandbox_logs.go
  packages/api/internal/handlers/sandbox_metrics.go
Labels: bug

#318 Add CI/CD to run infra unit tests on new PRs
  .github/workflows/pr-tests.yml
  Makefile
  packages/api/Makefile
  packages/client-proxy/Makefile
  packages/docker-reverse-proxy/Makefile
  packages/envd/Makefile
  packages/orchestrator/Makefile
  packages/shared/Makefile
  packages/template-manager/Makefile
Labels: improvement

#312 Run periodic tests in github actions to determine liveness
  .github/workflows/periodic-test.yml
  .gitignore
  tests/periodic-test/build-template/e2b.Dockerfile
  tests/periodic-test/build-template/index.ts
  tests/periodic-test/create-file.ts
  tests/periodic-test/run-code.ts
  tests/periodic-test/snapshot-and-resume.ts
Labels: improvement

#257 Add autopause handling to the API
  packages/api/internal/api/spec.gen.go
  packages/api/internal/api/types.gen.go
  packages/api/internal/cache/instance/instance.go
  packages/api/internal/cache/instance/operations.go
  packages/api/internal/handlers/sandbox.go
  packages/api/internal/handlers/sandbox_create.go
  packages/api/internal/handlers/sandbox_kill.go
  packages/api/internal/handlers/sandbox_pause.go
  packages/api/internal/handlers/sandbox_resume.go
  packages/api/internal/handlers/store.go
  packages/api/internal/orchestrator/cache.go
  packages/api/internal/orchestrator/create_instance.go
  packages/api/internal/orchestrator/delete_instance.go
  packages/api/internal/orchestrator/list_instances.go
  packages/api/internal/orchestrator/orchestrator.go
  packages/api/internal/orchestrator/pause_instance.go
  packages/shared/pkg/db/snapshot.go
  packages/shared/pkg/utils/set_once.go
  spec/openapi.yml
Labels: feature

#307 Add support for multiple domains on the same cluster
  Makefile
  main.tf
  packages/cluster/main.tf
  packages/cluster/network/main.tf
  packages/cluster/network/variables.tf
  packages/cluster/variables.tf
  variables.tf
Labels: feature

#323 Store auto pause field on the orchestrator
  packages/api/internal/orchestrator/create_instance.go
  packages/api/internal/orchestrator/list_instances.go
  packages/orchestrator/orchestrator.proto
  packages/shared/pkg/grpc/orchestrator/orchestrator.pb.go
  packages/shared/pkg/grpc/orchestrator/orchestrator_grpc.pb.go
Labels: bug

#327 Remove sandbox create rate limiting
  packages/api/internal/handlers/sandbox.go
  packages/api/internal/handlers/store.go
  packages/shared/pkg/meters/main.go
Labels: improvement

#325 Add create sandbox getLeastBusyNode retries
  packages/api/internal/api/spec.gen.go
  packages/api/internal/api/types.gen.go
  packages/api/internal/orchestrator/client.go
  packages/api/internal/orchestrator/create_instance.go
  packages/api/internal/orchestrator/node.go
  spec/openapi.yml
Labels: improvement

#329 Propagate new stopped at for sandbox to orchestrator
  packages/api/internal/handlers/sandbox_refresh.go
  packages/api/internal/handlers/sandbox_timeout.go
  packages/api/internal/orchestrator/keep_alive.go
  packages/api/internal/orchestrator/update_instance.go
Labels: bug

#297 orchestrator: process initialization and shut down
  packages/orchestrator/internal/dns/server.go
  packages/orchestrator/internal/server/main.go
  packages/orchestrator/main.go
Labels: improvement

#319 Split out and test post processing in template build
  packages/orchestrator/cmd/inspect-data/main.go
  packages/orchestrator/cmd/inspect-header/main.go
  packages/orchestrator/cmd/simulate-headers-merge/main.go
  packages/orchestrator/internal/sandbox/template/cache.go
  packages/shared/pkg/storage/gcs/bucket.go
  packages/shared/pkg/storage/gcs/client.go
  packages/shared/pkg/storage/template_build.go
  packages/template-manager/go.mod
  packages/template-manager/go.sum
  packages/template-manager/internal/build/network_linux.go
  packages/template-manager/internal/build/network_other.go
  packages/template-manager/internal/build/rootfs.go
  packages/template-manager/internal/build/rootfs_test.go
  packages/template-manager/internal/build/snapshot_linux.go
  packages/template-manager/internal/build/snapshot_other.go
  packages/template-manager/internal/template/storage.go
Labels: improvement

#320 Provision gcp logs data source for grafana with terraform
  main.tf
  terraform/grafana/README.md
  terraform/grafana/main.tf
Labels: improvement

#322 Cleanup GitHub Actions
  .github/workflows/heath-check.yml
  .github/workflows/periodic-test.yml
  .github/workflows/release.yml
Labels: improvement

#334 Add basic logging of grpc calls to the orchestrator
  packages/orchestrator/go.mod
  packages/orchestrator/go.sum
  packages/orchestrator/internal/server/main.go
Labels: improvement

#328 Add custom cache for sandbox lifecycle
  packages/api/internal/cache/instance/instance.go
  packages/api/internal/cache/instance/lifecycle_cache.go
  packages/api/internal/cache/instance/lifecycle_cache_test.go
  packages/api/internal/cache/instance/monitoring.go
  packages/api/internal/cache/instance/operations.go
  packages/api/internal/cache/instance/reservation.go
  packages/api/internal/cache/instance/sync.go
  packages/api/internal/handlers/sandbox_get.go
  packages/api/internal/handlers/sandboxes_list.go
  packages/api/internal/orchestrator/cache.go
  packages/api/internal/orchestrator/create_instance.go
  packages/api/internal/orchestrator/keep_alive.go
  packages/api/internal/orchestrator/list_instances.go
  packages/api/internal/orchestrator/node.go
  packages/api/internal/orchestrator/orchestrator.go
Labels: bug, improvement

#336 Improve sandbox create retry log, exit on context done
  packages/api/internal/orchestrator/create_instance.go
Labels: improvement

#275 Separate GitHub tf from infra terraform
  .terraform.lock.hcl
  Makefile
  github-tf/.terraform.lock.hcl
  github-tf/Makefile
  github-tf/main.tf
  github-tf/variables.tf
  main.tf
  variables.tf
Labels: improvement

#342 Cleanup metrics and temporarily increase the interval
  packages/orchestrator/internal/sandbox/checks.go
  packages/orchestrator/internal/server/sandboxes.go
Labels: bug, improvement

#339 Fix leaks in orchestator
  packages/orchestrator/internal/sandbox/fc/process.go
Labels: bug

#338 Automatically reconnect to newly deployed template manager
  packages/api/internal/handlers/template_start_build.go
  packages/api/internal/template-manager/client.go
  packages/shared/pkg/grpc/connection.go
  packages/template-manager/internal/server/main.go
Labels: bug

#344 Set our logger as a global one
  packages/shared/pkg/logging/logger.go
Labels: improvement

#343 Try to fix NBD panic
  packages/orchestrator/internal/sandbox/nbd/dispatch.go
  packages/orchestrator/internal/sandbox/nbd/path_direct.go
Labels: bug

#345 Add initial commit logs
  packages/api/Dockerfile
  packages/api/Makefile
  packages/api/main.go
  packages/client-proxy/Dockerfile
  packages/client-proxy/Makefile
  packages/client-proxy/main.go
  packages/docker-reverse-proxy/Dockerfile
  packages/docker-reverse-proxy/Makefile
  packages/docker-reverse-proxy/main.go
  packages/orchestrator/Dockerfile
  packages/orchestrator/Makefile
  packages/orchestrator/main.go
  packages/template-manager/Makefile
  packages/template-manager/main.go
Labels: improvement

#346 Add logs and timeouts
  packages/api/internal/api/spec.gen.go
  packages/api/internal/api/types.gen.go
  packages/api/internal/cache/instance/instance.go
  packages/api/internal/handlers/sandbox_create.go
  packages/api/internal/orchestrator/cache.go
  packages/api/internal/orchestrator/create_instance.go
  packages/api/internal/orchestrator/node.go
  packages/api/internal/orchestrator/orchestrator.go
  packages/orchestrator/internal/sandbox/sandbox.go
  packages/orchestrator/internal/server/sandboxes.go
  packages/shared/pkg/smap/smap.go
  spec/openapi.yml
Labels: improvement
