Repository e2b-dev/infra, pull requests merged in 2025-09, with the labels that each got.

#1095 Remove parallel tests
  packages/api/internal/orchestrator/placement/placement.go
  tests/integration/internal/tests/api/sandbox_internet_test.go
  tests/integration/internal/tests/envd/localhost_bind_test.go
Labels: bug

#1098 Sqlc is not able to get arg type when we are fist filteriing by empty jsonb object
  packages/db/queries/get_snapshots_with_cursor.sql
Labels: bug

#1097 Fix autopause
  packages/api/internal/api/spec.gen.go
  packages/api/internal/cache/instance/instance.go
  packages/api/internal/cache/instance/operations.go
  packages/api/internal/orchestrator/cache.go
  packages/api/internal/orchestrator/pause_instance.go
  spec/openapi.yml
Labels: bug

#1077 Add feature flags for placing algorithm
  packages/api/internal/handlers/sandboxes_list.go
  packages/api/internal/handlers/store.go
  packages/api/internal/orchestrator/create_instance.go
  packages/api/internal/orchestrator/orchestrator.go
  packages/api/internal/orchestrator/placement/placement.go
  packages/api/internal/orchestrator/placement/placement_best_of_K.go
  packages/api/internal/orchestrator/placement/placement_best_of_K_test.go
  packages/api/internal/orchestrator/placement/placement_least_busy.go
  packages/api/internal/orchestrator/placement/placement_test.go
  packages/orchestrator/internal/metrics/sandboxes.go
  packages/shared/pkg/feature-flags/client.go
  packages/shared/pkg/feature-flags/flags.go
  packages/shared/pkg/limit/limiter.go
Labels: feature

#1099 Fix regression for envd watcher
  packages/envd/internal/services/filesystem/watch_sync.go
  tests/integration/internal/tests/envd/watcher_test.go
Labels: bug

#1094 Decrease log level for user errors
  packages/api/go.mod
  packages/api/go.sum
  packages/api/internal/middleware/logging.go
  packages/api/main.go
Labels: improvement

#1103 Fix panic when build not found because concurrent access
  Makefile
  packages/api/internal/api/spec.gen.go
  packages/api/internal/api/types.gen.go
  packages/api/internal/cache/templates/cache.go
  packages/api/internal/handlers/sandbox_create.go
  packages/api/internal/handlers/template_request_build.go
  packages/api/internal/handlers/templates_list.go
  packages/db/Makefile
  packages/db/migrations/20000101000000_auth.sql
  packages/db/queries/get_team_templates.sql
  packages/db/queries/get_team_templates.sql.go
  packages/db/queries/models.go
  packages/db/scripts/migrator.go
  packages/docker-reverse-proxy/go.mod
  packages/docker-reverse-proxy/go.sum
  packages/shared/pkg/db/envs.go
  spec/openapi.yml
  tests/integration/internal/api/models.gen.go
Labels: bug

#1106 Add multiple template managers in Nomad job
  packages/nomad/template-manager.hcl
Labels: improvement

#1111 Prevent restarts only for orchestrators
  packages/orchestrator/main.go
Labels: bug

#1119 Update devcontainer.json setup
  .devcontainer/devcontainer.json
Labels: improvement

#1120 Fix change status endpoint to use node ID
  packages/api/internal/handlers/admin.go
  packages/api/internal/orchestrator/admin.go
  packages/api/internal/orchestrator/client.go
Labels: bug

#1131 Move the events from models packages
  packages/orchestrator/internal/events/sandbox_events_service.go
  packages/orchestrator/internal/server/main.go
  packages/orchestrator/internal/server/sandboxes.go
  packages/orchestrator/main.go
  packages/shared/pkg/events/event/sandbox_event.go
  packages/shared/pkg/events/webhooks/webhooks.go
Labels: bug

#1130 Improve clarity and grammar in README.md
  packages/envd/README.md
Labels: docs

#1127 Allow setting status for other clusters
  packages/api/internal/api/spec.gen.go
  packages/api/internal/api/types.gen.go
  packages/api/internal/handlers/admin.go
  packages/api/internal/orchestrator/admin.go
  packages/api/internal/orchestrator/client.go
  spec/openapi.yml
  tests/integration/internal/api/models.gen.go
Labels: bug

#1122 Return total count for running sandboxes
  packages/api/internal/handlers/sandboxes_list.go
  tests/integration/internal/tests/api/sandbox_list_test.go
Labels: improvement

#1137 Run tf init in iac provider folder
  .github/actions/deploy-setup/action.yml
Labels: bug

#1138 Template manager - Remove incorrect arguments, add stagger
  iac/provider-gcp/nomad/jobs/template-manager.hcl
Labels: bug

#1128 Refactor template build cache to use sqlc
  packages/api/internal/cache/templates/cache.go
  packages/api/internal/handlers/sandbox.go
  packages/api/internal/handlers/sandbox_kill.go
  packages/api/internal/handlers/sandbox_resume.go
  packages/api/internal/handlers/store.go
  packages/api/internal/handlers/template_build_status.go
  packages/api/internal/handlers/template_delete.go
  packages/api/internal/handlers/template_request_build.go
  packages/api/internal/handlers/template_start_build.go
  packages/api/internal/handlers/template_start_build_v2.go
  packages/api/internal/orchestrator/create_instance.go
  packages/api/internal/orchestrator/orchestrator.go
  packages/api/internal/orchestrator/pause_instance.go
  packages/api/internal/template-manager/template_status.go
  packages/db/migrations/20250905134524_fix_env_builds_non_null_fields.sql
  packages/db/queries/get_template_build.sql
  packages/db/queries/get_template_build.sql.go
  packages/db/queries/models.go
  packages/db/queries/update_template_build_status.sql
  packages/db/queries/update_template_build_status.sql.go
  packages/db/sqlc.yaml
  packages/db/types/types.go
  packages/shared/pkg/db/env_aliases.go
  packages/shared/pkg/db/envs.go
  packages/shared/pkg/db/errors.go
  packages/shared/pkg/models/env_query.go
  packages/shared/pkg/models/envbuild.go
  packages/shared/pkg/models/envbuild/envbuild.go
  packages/shared/pkg/models/envbuild/where.go
  packages/shared/pkg/models/envbuild_create.go
  packages/shared/pkg/models/envbuild_query.go
  packages/shared/pkg/models/envbuild_update.go
  packages/shared/pkg/models/event/sandbox_event.go
  packages/shared/pkg/models/migrate/schema.go
  packages/shared/pkg/models/mutation.go
  packages/shared/pkg/models/runtime.go
  packages/shared/pkg/models/webhooks/webhooks.go
  packages/shared/pkg/schema/build.go
Labels: improvement

#1148 Skip evict if the sandbox is already being removed
  packages/api/internal/orchestrator/evictor/evict.go
Labels: bug

#1152 Nomad service discovery for Edge API
  iac/provider-gcp/nomad/jobs/edge.hcl
  iac/provider-gcp/nomad/main.tf
  packages/client-proxy/Makefile
  packages/client-proxy/go.mod
  packages/client-proxy/go.sum
  packages/client-proxy/internal/service-discovery/builder.go
  packages/client-proxy/internal/service-discovery/ec2-service-discovery.go
  packages/client-proxy/internal/service-discovery/nomad-service-discovery.go
Labels: improvement

#1171 Report envd version for clock drift warns
  packages/orchestrator/internal/metrics/sandboxes.go
Labels: improvement

#1173 Make it possible to customize API resources
  iac/provider-gcp/Makefile
  iac/provider-gcp/main.tf
  iac/provider-gcp/nomad/jobs/api.hcl
  iac/provider-gcp/nomad/main.tf
  iac/provider-gcp/nomad/variables.tf
  iac/provider-gcp/variables.tf
Labels: improvement

#1176 Run OTEL with hugepages metrics
  iac/provider-gcp/nomad/configs/otel-collector.yaml
  iac/provider-gcp/nomad/jobs/otel-collector.hcl
  packages/otel-collector/Makefile
Labels: feature

#1178 Run pull request jobs on all pull requests
  .github/workflows/pull-request.yml
Labels: improvement

#1182 Add missing prefix for additional services
  iac/provider-gcp/nomad-cluster/nodepool-api.tf
Labels: bug

#1184 Increase ready command timeout
  packages/orchestrator/internal/template/build/phases/finalize/ready.go
Labels: improvement

#1191 Remove delay from template manager deploy
  iac/provider-gcp/nomad/jobs/template-manager.hcl
Labels: improvement

#1194 Add attributes to template build error
  packages/orchestrator/internal/template/server/create_template.go
Labels: improvement

#1199 Upgrade golangci-lint to 2.4.0
  .github/workflows/lint.yml
  .tool-versions
  Makefile
Labels: improvement

#1204 Add the mirror linter
  .golangci.yml
  packages/envd/internal/services/legacy/conversion_test.go
Labels: improvement

#1198 Add unconvert linter, remove unnecessary conversions
  .golangci.yml
  packages/api/internal/handlers/sandboxes_list.go
  packages/api/internal/middleware/otel/metrics/middleware.go
  packages/orchestrator/internal/sandbox/block/cache.go
  packages/orchestrator/internal/sandbox/uffd/serve.go
  packages/orchestrator/internal/sandbox/uffd/userfaultfd/constants.go
  packages/orchestrator/main.go
  tests/integration/internal/tests/api/sandboxes/sandbox_list_test.go
Labels: improvement

#1188 Verify all generated code is up to date
  .github/workflows/pr-go-integrity.yml
  .github/workflows/pr-no-generated-changes.yml
  .github/workflows/pull-request.yml
  .github/workflows/push-main.yml
  Makefile
  packages/shared/pkg/storage/header/inspect.go
  scripts/fix-tracers.sh
  scripts/golang-dependencies-integrity.sh
Labels: improvement

#1206 add nilnesserr linter, fix some error reporting
  .golangci.yml
  packages/orchestrator/internal/sandbox/sandbox.go
Labels: improvement

#1207 Add the ineffassign linter
  .golangci.yml
Labels: improvement

#1219 Remove template build spammy logs
  packages/api/internal/cache/templates/cache.go
  packages/api/internal/template-manager/template_status.go
Labels: bug

#1183 Migrate base template to new template sdk
  packages/shared/Makefile
  packages/shared/scripts/.gitignore
  packages/shared/scripts/build.prod.ts
  packages/shared/scripts/e2b.Dockerfile
  packages/shared/scripts/e2b.toml
  packages/shared/scripts/package-lock.json
  packages/shared/scripts/package.json
  packages/shared/scripts/template.ts
Labels: improvement

#1221 Fix Docker build with go 1.24.7
  packages/api/Dockerfile
  packages/client-proxy/Dockerfile
  packages/docker-reverse-proxy/Dockerfile
Labels: bug

#1220 feat: Add subdomain support for Cloudflare DNS
  .env.template
  iac/provider-gcp/nomad-cluster/network/main.tf
Labels: feature

#1190 Remove some more embedded contexts: Chunker, FileSystemStorageObjectProvider
  packages/orchestrator/cmd/mock-nbd/mock.go
  packages/orchestrator/internal/sandbox/block/chunk.go
  packages/orchestrator/internal/sandbox/block/device.go
  packages/orchestrator/internal/sandbox/block/empty.go
  packages/orchestrator/internal/sandbox/block/local.go
  packages/orchestrator/internal/sandbox/block/overlay.go
  packages/orchestrator/internal/sandbox/block/tracker.go
  packages/orchestrator/internal/sandbox/build/build.go
  packages/orchestrator/internal/sandbox/build/diff.go
  packages/orchestrator/internal/sandbox/build/local_diff.go
  packages/orchestrator/internal/sandbox/build/storage_diff.go
  packages/orchestrator/internal/sandbox/nbd/dispatch.go
  packages/orchestrator/internal/sandbox/sandbox.go
  packages/orchestrator/internal/sandbox/template/storage.go
  packages/orchestrator/internal/sandbox/uffd/handler.go
  packages/orchestrator/internal/sandbox/uffd/memory_backend.go
  packages/orchestrator/internal/sandbox/uffd/noop.go
  packages/orchestrator/internal/sandbox/uffd/serve.go
  packages/shared/pkg/storage/storage_fs.go
Labels: improvement

#1225 Invert the list of linters
  .golangci.yml
  packages/client-proxy/internal/edge-pass-through/events.go
  packages/shared/pkg/storage/gcp_multipart_test.go
Labels: improvement

#1159 API - Sandbox locking
  packages/api/internal/cache/instance/instance.go
  packages/api/internal/cache/instance/instance_test.go
  packages/api/internal/cache/instance/operations.go
  packages/api/internal/cache/instance/reservation.go
  packages/api/internal/cache/instance/reservation_test.go
  packages/api/internal/cache/instance/store.go
  packages/api/internal/cache/instance/sync.go
  packages/api/internal/handlers/sandbox.go
  packages/api/internal/handlers/sandbox_get.go
  packages/api/internal/handlers/sandbox_kill.go
  packages/api/internal/handlers/sandbox_pause.go
  packages/api/internal/handlers/sandbox_resume.go
  packages/api/internal/handlers/sandboxes_list.go
  packages/api/internal/orchestrator/admin.go
  packages/api/internal/orchestrator/analytics.go
  packages/api/internal/orchestrator/cache.go
  packages/api/internal/orchestrator/create_instance.go
  packages/api/internal/orchestrator/delete_instance.go
  packages/api/internal/orchestrator/errors.go
  packages/api/internal/orchestrator/evictor/evict.go
  packages/api/internal/orchestrator/keep_alive.go
  packages/api/internal/orchestrator/keep_alive_test.go
  packages/api/internal/orchestrator/lifecycle.go
  packages/api/internal/orchestrator/list_instances.go
  packages/api/internal/orchestrator/nodemanager/metrics.go
  packages/api/internal/orchestrator/nodemanager/sandboxes.go
  packages/api/internal/orchestrator/orchestrator.go
  packages/api/internal/orchestrator/pause_instance.go
  packages/api/internal/orchestrator/placement/placement_benchmark_test.go
  tests/integration/internal/tests/api/sandboxes/sandbox_kill_test.go
Labels: improvement

#1228 Enable the 'defer' revive rule
  .golangci.yml
  packages/shared/pkg/utils/resizable_semaphore_test.go
Labels: improvement

#1224 add embeddedstructfieldcheck linter
  .golangci.yml
  packages/api/internal/orchestrator/nodemanager/mock.go
  packages/api/internal/orchestrator/placement/placement_benchmark_test.go
  packages/api/internal/utils/sandboxes_list.go
  packages/clickhouse/pkg/batcher/product_usage_insert_batcher.go
  packages/clickhouse/pkg/batcher/sandbox_events_insert_batcher.go
  packages/db/client/client.go
  packages/orchestrator/internal/sandbox/build/local_diff.go
  packages/orchestrator/internal/template/build/writer/filtered_writer.go
  packages/orchestrator/internal/template/server/main.go
  packages/shared/pkg/proxy/pool/client.go
  packages/shared/pkg/proxy/proxy.go
  packages/shared/pkg/proxy/tracking/connection.go
  packages/shared/pkg/proxy/tracking/listener.go
  packages/shared/pkg/storage/sandbox.go
  packages/shared/pkg/storage/storage_fs.go
  packages/shared/pkg/storage/template_cache.go
Labels: improvement

#1231 Remove noisy log from API
  packages/api/internal/dns/server.go
Labels: improvement

#1229 Enable the 'indent-error-flow' revive rule
  .golangci.yml
  packages/api/internal/orchestrator/placement/placement_best_of_K.go
  packages/client-proxy/internal/proxy/proxy.go
  packages/orchestrator/internal/sandbox/build/cache.go
  packages/orchestrator/internal/sandbox/sandbox.go
  packages/orchestrator/internal/template/build/phases/base/builder.go
  packages/orchestrator/internal/template/build/phases/finalize/ready.go
  packages/orchestrator/internal/template/server/upload_layer_files_template.go
Labels: improvement

#1236 Add hit/miss metrics for template caching
  packages/orchestrator/internal/sandbox/template/cache.go
Labels: improvement

#1250 Refactor template request common methods
  packages/api/internal/handlers/auth.go
  packages/api/internal/handlers/template_request_build.go
  packages/api/internal/handlers/template_request_build_v2.go
  packages/api/internal/team/limits.go
  packages/api/internal/template/register_build.go
Labels: go

#1257 Fix symlink file move after unpacking the archive
  packages/orchestrator/internal/template/build/commands/copy.go
Labels: bug

#1260 Fix concurrent hosts file write during sbx start
  packages/envd/internal/api/init.go
  packages/envd/internal/api/store.go
  packages/envd/main.go
Labels: bug

#1205 Add the noctx linter
  .golangci.yml
  packages/client-proxy/main.go
  packages/db/scripts/migrator.go
  packages/docker-reverse-proxy/internal/handlers/token.go
  packages/envd/internal/port/forward.go
  packages/envd/main.go
  packages/orchestrator/cmd/build-template/main.go
  packages/orchestrator/cmd/clean-nfs-cache/main.go
  packages/orchestrator/internal/grpcserver/server.go
  packages/orchestrator/internal/proxy/proxy.go
  packages/orchestrator/internal/sandbox/checks.go
  packages/orchestrator/internal/sandbox/fc/process.go
  packages/orchestrator/internal/sandbox/health.go
  packages/orchestrator/internal/sandbox/sandbox.go
  packages/orchestrator/internal/server/sandboxes.go
  packages/orchestrator/internal/template/build/core/envd/envd.go
  packages/orchestrator/internal/template/build/core/filesystem/ext4.go
  packages/orchestrator/internal/template/build/core/oci/oci.go
  packages/orchestrator/internal/template/build/core/rootfs/rootfs.go
  packages/orchestrator/internal/template/build/phases/base/builder.go
  packages/orchestrator/internal/template/build/phases/base/provision.go
  packages/orchestrator/internal/template/build/sandboxtools/file.go
  packages/orchestrator/main.go
  packages/shared/pkg/proxy/proxy.go
  packages/shared/pkg/proxy/proxy_test.go
Labels: improvement

#1262 Convert any to native types
  packages/api/internal/cache/templates/cache.go
  packages/api/internal/orchestrator/nodemanager/node.go
  packages/api/internal/orchestrator/nodemanager/status.go
  packages/api/internal/orchestrator/nodemanager/sync.go
  packages/api/internal/template-manager/template_status.go
  packages/client-proxy/internal/edge/pool/orchestrator.go
  packages/orchestrator/internal/server/main.go
  packages/orchestrator/internal/template/cache/build_cache.go
Labels: bug

#1264 Pass timestamp from orchestrator
  packages/envd/internal/api/api.gen.go
  packages/envd/internal/api/init.go
  packages/envd/main.go
  packages/envd/spec/envd.yaml
  packages/orchestrator/internal/sandbox/envd.go
  tests/integration/internal/envd/api/models.gen.go
Labels: bug

#1254 Move the template spawn counter to sqlc
  packages/api/internal/handlers/store.go
  packages/api/internal/utils/counter.go
  packages/db/queries/update_template_spawns.sql
  packages/db/queries/update_template_spawns.sql.go
  packages/shared/pkg/db/envs.go
Labels: improvement

#1245 Split the store and sandbox data
  packages/api/internal/handlers/sandbox_create.go
  packages/api/internal/handlers/sandbox_get.go
  packages/api/internal/handlers/sandbox_kill.go
  packages/api/internal/handlers/sandbox_pause.go
  packages/api/internal/handlers/sandbox_refresh.go
  packages/api/internal/handlers/sandbox_resume.go
  packages/api/internal/handlers/sandboxes_list.go
  packages/api/internal/metrics/team.go
  packages/api/internal/orchestrator/analytics.go
  packages/api/internal/orchestrator/cache.go
  packages/api/internal/orchestrator/create_instance.go
  packages/api/internal/orchestrator/delete_instance.go
  packages/api/internal/orchestrator/evictor/evict.go
  packages/api/internal/orchestrator/lifecycle.go
  packages/api/internal/orchestrator/list_instances.go
  packages/api/internal/orchestrator/nodemanager/metrics.go
  packages/api/internal/orchestrator/nodemanager/sandboxes.go
  packages/api/internal/orchestrator/nodemanager/sync.go
  packages/api/internal/orchestrator/orchestrator.go
  packages/api/internal/orchestrator/pause_instance.go
  packages/api/internal/orchestrator/placement/placement_benchmark_test.go
  packages/api/internal/sandbox/errors.go
  packages/api/internal/sandbox/sandbox.go
  packages/api/internal/sandbox/states.go
  packages/api/internal/sandbox/store.go
  packages/api/internal/sandbox/store/memory/operations.go
  packages/api/internal/sandbox/store/memory/operations_test.go
  packages/api/internal/sandbox/store/memory/reservation.go
  packages/api/internal/sandbox/store/memory/reservation_test.go
  packages/api/internal/sandbox/store/memory/sandbox.go
  packages/api/internal/sandbox/store/memory/store.go
  packages/api/internal/sandbox/store/memory/sync.go
Labels: improvement
