Repository e2b-dev/infra, pull requests merged in 2025-06, with the labels that each got.

#727 Fix API keys seed db
  packages/shared/scripts/seed/postgres/seed-db.go
  tests/integration/seed.go
Labels: bug

#728 Delete snapshots in the background
  packages/api/internal/handlers/sandbox_kill.go
Labels: improvement

#602 Setup clickhouse in cluster mode
  .env.template
  Makefile
  main.tf
  packages/api/main.tf
  packages/buckets/main.tf
  packages/buckets/outputs.tf
  packages/cluster/clickhouse-cluster/main.tf
  packages/cluster/clickhouse-cluster/variables.tf
  packages/cluster/main.tf
  packages/cluster/scripts/run-clickhouse-nomad.sh
  packages/cluster/scripts/start-clickhouse.sh
  packages/cluster/variables.tf
  packages/init/main.tf
  packages/init/outputs.tf
  packages/nomad/clickhouse.hcl
  packages/nomad/main.tf
  packages/nomad/variables.tf
  variables.tf
Labels: feature

#723 Expose provision logs during template build
  packages/nomad/template-manager.hcl
  packages/orchestrator/internal/grpcserver/server.go
  packages/orchestrator/internal/sandbox/fc/process.go
  packages/orchestrator/internal/template/build/ext4/tools.go
  packages/orchestrator/internal/template/build/provision.sh
  packages/orchestrator/internal/template/build/rootfs.go
  packages/orchestrator/internal/template/build/template_builder.go
  packages/orchestrator/internal/template/build/writer/filtered_writer.go
Labels: improvement

#732 Use tags to distinguish between servers
  packages/nomad/clickhouse.hcl
  packages/nomad/main.tf
Labels: improvement

#729 Add ability to cancel running build
  packages/api/internal/handlers/template_start_build.go
  packages/orchestrator/cmd/build-template/main.go
  packages/orchestrator/internal/template/build/template_builder.go
  packages/orchestrator/internal/template/build/writer/postprocessor.go
  packages/orchestrator/internal/template/cache/build_cache.go
  packages/orchestrator/internal/template/server/create_template.go
  packages/orchestrator/internal/template/server/delete_template.go
  packages/orchestrator/internal/template/server/main.go
  packages/shared/pkg/meters/main.go
  packages/shared/pkg/utils/filter.go
  packages/shared/pkg/utils/map.go
  packages/shared/pkg/utils/map_values.go
Labels: improvement

#733 Add prefix to clickhouse cluster
  packages/cluster/clickhouse-cluster/variables.tf
  packages/cluster/main.tf
  packages/cluster/variables.tf
Labels: improvement

#730 Fix build failed status handling
  packages/api/internal/template-manager/template_manager.go
  packages/api/internal/template-manager/template_manager_test.go
Labels: bug

#734 Add missing default variable for template bucket
  main.tf
  variables.tf
Labels: bug

#735 Handle e2fsck repair exit codes
  packages/orchestrator/internal/template/build/ext4/tools.go
Labels: bug

#736 Remove datacenters from system jobs
  packages/nomad/logs-collector.hcl
  packages/nomad/otel-collector.hcl
Labels: bug

#738 Fix goroutine leak in nbd
  packages/orchestrator/internal/sandbox/nbd/dispatch.go
Labels: bug

#719 Add option for a template ready check
  packages/api/internal/api/spec.gen.go
  packages/api/internal/api/types.gen.go
  packages/api/internal/handlers/template_request_build.go
  packages/api/internal/handlers/template_start_build.go
  packages/api/internal/template-manager/create_template.go
  packages/db/migrations/20250528203546_ready_command.sql
  packages/db/queries/get_env_with_build.sql.go
  packages/db/queries/get_last_snapshot.sql.go
  packages/db/queries/get_snapshots_with_cursor.sql.go
  packages/db/queries/models.go
  packages/db/queries/teams___tiers__usersteams.sql.go
  packages/db/queries/teams_usersteams_join.sql.go
  packages/orchestrator/internal/template/build/command.go
  packages/orchestrator/internal/template/build/ready_command.go
  packages/orchestrator/internal/template/build/template_builder.go
  packages/orchestrator/internal/template/build/template_config.go
  packages/orchestrator/internal/template/server/create_template.go
  packages/orchestrator/template-manager.proto
  packages/shared/pkg/grpc/template-manager/template-manager.pb.go
  packages/shared/pkg/models/envbuild.go
  packages/shared/pkg/models/envbuild/envbuild.go
  packages/shared/pkg/models/envbuild/where.go
  packages/shared/pkg/models/envbuild_create.go
  packages/shared/pkg/models/envbuild_update.go
  packages/shared/pkg/models/migrate/schema.go
  packages/shared/pkg/models/mutation.go
  packages/shared/pkg/models/runtime.go
  packages/shared/pkg/schema/build.go
  spec/openapi.yml
Labels: feature

#744 envd: allow SDK headers in CORS
  packages/envd/main.go
Labels: improvement

#746 Handle gracefully already existing user
  packages/orchestrator/internal/template/build/configure.sh
Labels: bug

#741 Remove GCP from integration tests
  .github/actions/build-sandbox-template/action.yml
  .github/actions/host-init/action.yml
  .github/actions/host-init/init-client.sh
  .github/actions/start-services/action.yml
  packages/orchestrator/internal/template/build/template_builder.go
Labels: improvement

#747 Increase template waiting state deadline
  packages/api/internal/template-manager/template_manager.go
Labels: improvement

#751 Reconfigure regional instance group to better provision client nodes
  packages/cluster/client/main.tf
Labels: improvement

#740 Optimize team_api_keys schema
  packages/api/internal/handlers/accesstoken.go
  packages/api/internal/handlers/apikey.go
  packages/api/internal/team/apikeys.go
  packages/db/migrations/20250606204750_optimize_hashed_key_schema.sql
  packages/shared/pkg/keys/key.go
  packages/shared/pkg/keys/key_test.go
  packages/shared/pkg/models/accesstoken.go
  packages/shared/pkg/models/accesstoken/accesstoken.go
  packages/shared/pkg/models/accesstoken/where.go
  packages/shared/pkg/models/accesstoken_create.go
  packages/shared/pkg/models/migrate/schema.go
  packages/shared/pkg/models/mutation.go
  packages/shared/pkg/models/runtime.go
  packages/shared/pkg/models/teamapikey.go
  packages/shared/pkg/models/teamapikey/teamapikey.go
  packages/shared/pkg/models/teamapikey/where.go
  packages/shared/pkg/models/teamapikey_create.go
  packages/shared/pkg/models/teamapikey_update.go
  packages/shared/pkg/schema/access_token.go
  packages/shared/pkg/schema/team_api_key.go
  packages/shared/scripts/seed/postgres/seed-db.go
  tests/integration/seed.go
Labels: improvement

#759 Replace global telemetry usage with the local one
  packages/api/internal/cache/instance/instance.go
  packages/api/internal/cache/instance/reservation_test.go
  packages/api/internal/handlers/store.go
  packages/api/internal/middleware/otel/metrics/middleware.go
  packages/api/internal/middleware/otel/metrics/otelrecorder.go
  packages/api/internal/middleware/otel/metrics/version.go
  packages/api/internal/middleware/otel/tracing/middleware.go
  packages/api/internal/orchestrator/client.go
  packages/api/internal/orchestrator/orchestrator.go
  packages/api/internal/template-manager/client.go
  packages/api/internal/template-manager/template_manager.go
  packages/api/main.go
  packages/client-proxy/internal/proxy/proxy.go
  packages/client-proxy/main.go
  packages/nomad/otel-collector.hcl
  packages/orchestrator/cmd/build-template/main.go
  packages/orchestrator/cmd/mock-nbd/mock.go
  packages/orchestrator/internal/grpcserver/server.go
  packages/orchestrator/internal/proxy/proxy.go
  packages/orchestrator/internal/sandbox/nbd/pool.go
  packages/orchestrator/internal/sandbox/network/pool.go
  packages/orchestrator/internal/server/main.go
  packages/orchestrator/internal/template/cache/build_cache.go
  packages/orchestrator/internal/template/server/main.go
  packages/orchestrator/main.go
  packages/shared/pkg/logger/logger.go
  packages/shared/pkg/logger/sandbox/logger.go
  packages/shared/pkg/telemetry/config.go
  packages/shared/pkg/telemetry/logs.go
  packages/shared/pkg/telemetry/main.go
  packages/shared/pkg/telemetry/meters.go
  packages/shared/pkg/telemetry/metrics.go
  packages/shared/pkg/telemetry/otel.go
  packages/shared/pkg/telemetry/traces.go
Labels: improvement

#764 Change the sandbox start rate limit
  packages/cluster/network/main.tf
Labels: improvement

#767 Fix if max size isn't set
  packages/cluster/client/main.tf
Labels: bug

#768 Fix blocking sandbox logger
  packages/shared/pkg/logger/exporter.go
  packages/shared/pkg/logger/sandbox/logger.go
Labels: bug

#750 Return better errors for blocked teams via the API middleware
  packages/api/internal/auth/middleware.go
  packages/api/internal/handlers/store.go
  packages/api/internal/handlers/teams.go
  packages/api/internal/utils/error.go
  packages/nomad/otel-collector.hcl
  packages/shared/pkg/db/apiKeys.go
  tests/integration/Makefile
  tests/integration/internal/setup/api_client.go
  tests/integration/internal/setup/db_client.go
  tests/integration/internal/tests/team_test.go
Labels: improvement, go

#770 Turn off autoscale if autoscale not allowed
  packages/cluster/client/main.tf
Labels: bug

#771 Fix nodes sync race condition
  packages/api/internal/cache/instance/sync.go
Labels: bug

#773 Remove sandbox other
  packages/orchestrator/internal/sandbox/sandbox.go
  packages/orchestrator/internal/sandbox/sandbox_other.go
Labels: improvement

#772 Remove loki metrics
  packages/nomad/main.tf
  packages/nomad/orchestrator.hcl
  packages/nomad/variables.tf
  packages/orchestrator/internal/config/config.go
  packages/orchestrator/internal/sandbox/checks.go
  packages/orchestrator/internal/sandbox/metrics.go
  packages/orchestrator/internal/sandbox/sandbox.go
  packages/orchestrator/internal/server/main.go
  packages/orchestrator/internal/server/sandboxes.go
Labels: improvement

#774 Remove unused Loki metrics var
  main.tf
  variables.tf
Labels: bug

#781 Pass env vars from the Docker image to the start and ready commands
  packages/orchestrator/internal/template/build/build.go
  packages/orchestrator/internal/template/build/command.go
  packages/orchestrator/internal/template/build/oci/oci.go
  packages/orchestrator/internal/template/build/ready_command.go
  packages/orchestrator/internal/template/build/rootfs.go
  packages/orchestrator/internal/template/build/tar.go
  packages/orchestrator/internal/template/build/template_builder.go
  packages/shared/pkg/artifacts-registry/registry.go
  packages/shared/pkg/artifacts-registry/registry_aws.go
  packages/shared/pkg/artifacts-registry/registry_gcp.go
  packages/shared/pkg/artifacts-registry/registry_local.go
Labels: improvement

#769 Remove doubled Redis
  packages/api/internal/dns/server.go
  packages/api/internal/handlers/store.go
  packages/api/internal/orchestrator/orchestrator.go
  packages/nomad/api.hcl
  packages/nomad/main.tf
Labels: improvement

#785 Fix external sandbox logs from services
  packages/api/main.go
  packages/client-proxy/main.go
  packages/orchestrator/cmd/build-template/main.go
  packages/orchestrator/main.go
  packages/shared/pkg/logger/logger.go
  packages/shared/pkg/logger/sandbox/logger.go
Labels: bug

#778 Setup Launchdarkly for clickhouse
  packages/nomad/main.tf
  packages/nomad/orchestrator.hcl
  packages/orchestrator/go.mod
  packages/orchestrator/go.sum
  packages/orchestrator/internal/config/config.go
  packages/orchestrator/internal/sandbox/checks.go
  packages/orchestrator/internal/sandbox/sandbox.go
  packages/orchestrator/internal/server/main.go
  packages/orchestrator/internal/server/sandboxes.go
  packages/orchestrator/main.go
  packages/shared/pkg/feature-flags/client.go
  packages/shared/pkg/feature-flags/client_test.go
  packages/shared/pkg/feature-flags/flags.go
Labels: improvement

#786 Replace our own abstraction on top of the redis client
  packages/api/internal/dns/server.go
  packages/api/internal/handlers/store.go
  packages/api/internal/orchestrator/orchestrator.go
Labels: improvement

#776 Update confirm script
  .github/workflows/build-and-upload-job.yml
  .github/workflows/deploy-infra.yml
  .github/workflows/deploy-job.yml
  Makefile
  scripts/confirm.sh
Labels: improvement

#780 Distinguish between newly created and synced sandboxes when inserting to sandbox cache
  packages/api/internal/cache/instance/instance.go
  packages/api/internal/cache/instance/operations.go
  packages/api/internal/orchestrator/cache.go
Labels: improvement

#788 Run Clickhouse if nodes available
  packages/nomad/main.tf
Labels: improvement

#783 Improve Otel Collector - Add node name, drop unused labels
  packages/nomad/clickhouse.hcl
  packages/nomad/configs/clickhouse-otel-agent.yaml
  packages/nomad/configs/otel-collector.yaml
  packages/nomad/main.tf
  packages/nomad/otel-collector.hcl
  packages/nomad/variables.tf
Labels: improvement

#794 Make cluster source image version fixed to specific release
  packages/cluster-disk-image/main.pkr.hcl
Labels: bug

#796 Clickhouse nomad job update config
  Makefile
  main.tf
  packages/nomad/clickhouse.hcl
  packages/nomad/main.tf
  packages/nomad/variables.tf
  variables.tf
Labels: improvement

#797 Add benchmark clickhouse script
  packages/orchestrator/cmd/benchmark-metrics/main.go
  packages/orchestrator/internal/server/main.go
  packages/orchestrator/main.go
  packages/shared/pkg/telemetry/sandbox.go
Labels: feature

#808 Add API migrator
  .github/workflows/deploy-infra.yml
  Makefile
  packages/db/Dockerfile
  packages/db/Makefile
  packages/db/go.mod
  packages/db/scripts/migrator.go
  packages/nomad/api.hcl
  packages/nomad/main.tf
Labels: feature

#795 BYOC: Edge cluster pool implementation
  packages/api/internal/edge/edge.go
  packages/api/internal/handlers/store.go
  packages/db/migrations/20250606213446_deployment_cluster.sql
  packages/db/queries/get_active_clusters.sql
  packages/db/queries/get_active_clusters.sql.go
  packages/db/queries/models.go
  packages/db/queries/teams___tiers__usersteams.sql.go
  packages/db/queries/teams_usersteams_join.sql.go
  packages/shared/pkg/logger/fields.go
  packages/shared/pkg/models/client.go
  packages/shared/pkg/models/cluster.go
  packages/shared/pkg/models/cluster/cluster.go
  packages/shared/pkg/models/cluster/where.go
  packages/shared/pkg/models/cluster_create.go
  packages/shared/pkg/models/cluster_delete.go
  packages/shared/pkg/models/cluster_query.go
  packages/shared/pkg/models/cluster_update.go
  packages/shared/pkg/models/ent.go
  packages/shared/pkg/models/hook/hook.go
  packages/shared/pkg/models/internal/schemaconfig.go
  packages/shared/pkg/models/migrate/schema.go
  packages/shared/pkg/models/mutation.go
  packages/shared/pkg/models/predicate/predicate.go
  packages/shared/pkg/models/runtime.go
  packages/shared/pkg/models/team.go
  packages/shared/pkg/models/team/team.go
  packages/shared/pkg/models/team/where.go
  packages/shared/pkg/models/team_create.go
  packages/shared/pkg/models/team_update.go
  packages/shared/pkg/models/tx.go
  packages/shared/pkg/schema/cluster.go
  packages/shared/pkg/schema/team.go
Labels: feature

#809 Removed dummy GRPC client
  packages/api/internal/analytics_collector/client.go
  packages/api/internal/cache/instance/instance.go
  packages/api/internal/cache/instance/reservation_test.go
  packages/api/internal/orchestrator/analytics.go
  packages/api/internal/orchestrator/cache.go
  packages/api/internal/orchestrator/client.go
  packages/api/internal/orchestrator/orchestrator.go
  packages/api/internal/template-manager/client.go
  packages/client-proxy/internal/edge/pool/orchestrator.go
  packages/shared/pkg/grpc/connection.go
  packages/shared/pkg/grpc/dummy_client.go
Labels: improvement

#802 Increase inodes count
  go.work.sum
  packages/orchestrator/go.mod
  packages/orchestrator/go.sum
  packages/orchestrator/internal/template/build/ext4/tools.go
  packages/orchestrator/internal/template/build/oci/oci.go
  packages/orchestrator/internal/template/build/oci/oci_test.go
  packages/orchestrator/internal/template/build/rootfs.go
  packages/orchestrator/internal/template/build/template_builder.go
  packages/shared/pkg/artifacts-registry/registry_local.go
Labels: improvement

#813 Check for envd version before trying to scrape metrics
  packages/orchestrator/internal/sandbox/checks.go
Labels: bug

#820 Rewrite GRPC connection
  packages/api/go.mod
  packages/api/go.sum
  packages/api/internal/analytics_collector/client.go
  packages/api/internal/orchestrator/client.go
  packages/api/internal/template-manager/client.go
  packages/client-proxy/go.mod
  packages/client-proxy/go.sum
  packages/client-proxy/internal/edge/pool/orchestrator-pool.go
  packages/client-proxy/internal/edge/pool/orchestrator.go
  packages/client-proxy/main.go
  packages/shared/pkg/grpc/connection.go
  tests/integration/internal/setup/orchestrator_client.go
Labels: improvement, go

#821 Fix template manager connection
  packages/api/internal/template-manager/client.go
  packages/nomad/api.hcl
  packages/nomad/main.tf
Labels: bug

#822 Refactor sandbox metrics observer
  packages/api/go.mod
  packages/api/internal/handlers/sandbox_create.go
  packages/api/internal/utils/map.go
  packages/db/go.mod
  packages/orchestrator/cmd/benchmark-metrics/main.go
  packages/orchestrator/go.mod
  packages/orchestrator/internal/metrics/sandboxes.go
  packages/orchestrator/internal/sandbox/checks.go
  packages/orchestrator/internal/sandbox/health.go
  packages/orchestrator/internal/sandbox/metrics.go
  packages/orchestrator/internal/sandbox/sandbox.go
  packages/orchestrator/internal/server/main.go
  packages/orchestrator/internal/server/sandboxes.go
  packages/orchestrator/main.go
  packages/shared/go.mod
  packages/shared/pkg/telemetry/sandbox.go
  packages/shared/pkg/utils/context.go
  packages/shared/pkg/utils/version.go
Labels: bug

#818 Update self-host.md to contain Google Cloud Quota troubleshoot guide
  self-host.md
Labels: docs

#825 API - Orchestrator status - Return unhealthy if cant connect
  packages/api/internal/orchestrator/cache.go
  packages/api/internal/orchestrator/client.go
  packages/api/internal/orchestrator/metrics.go
  packages/api/internal/orchestrator/node.go
  packages/api/internal/orchestrator/orchestrator.go
  packages/shared/pkg/telemetry/meters.go
Labels: bug, improvement

#832 Send resource info to the collector
  packages/api/internal/analytics_collector/collector.pb.go
  packages/api/internal/analytics_collector/collector_grpc.pb.go
  packages/api/internal/orchestrator/cache.go
Labels: improvement

#836 Fix overlayfs mount with more than 4096 chars
  packages/orchestrator/internal/template/build/ext4/tools.go
Labels: bug
