Repository e2b-dev/infra, pull requests merged in 2025-08, with the labels that each got.

#940 Add DiskSizeMB field
  packages/api/internal/api/spec.gen.go
  packages/api/internal/api/types.gen.go
  packages/api/internal/handlers/sandbox_get.go
  packages/api/internal/handlers/sandboxes_list.go
  packages/api/internal/handlers/templates_list.go
  packages/api/internal/orchestrator/node.go
  packages/docker-reverse-proxy/go.mod
  packages/docker-reverse-proxy/go.sum
  packages/shared/pkg/db/envs.go
  spec/openapi.yml
  tests/integration/go.mod
  tests/integration/go.sum
Labels: improvement

#948 Make metrics long sandbox ID compatible
  packages/api/internal/handlers/sandbox_metrics.go
  packages/api/internal/handlers/sandboxes_list_metrics.go
Labels: bug

#953 Fix build user creation
  packages/orchestrator/internal/template/build/command/user.go
Labels: bug

#950 Remove pointer from team and build on instance info
  packages/api/internal/cache/instance/instance.go
  packages/api/internal/cache/instance/operations.go
  packages/api/internal/cache/instance/reservation.go
  packages/api/internal/cache/instance/reservation_test.go
  packages/api/internal/handlers/sandbox_get.go
  packages/api/internal/handlers/sandbox_kill.go
  packages/api/internal/handlers/sandbox_pause.go
  packages/api/internal/orchestrator/cache.go
  packages/api/internal/orchestrator/create_instance.go
  packages/api/internal/orchestrator/list_instances.go
Labels: improvement

#961 Speed up tests base build
  .github/actions/build-sandbox-template/action.yml
  packages/orchestrator/cmd/build-template/main.go
Labels: improvement

#965 Refactor UFFD mapping handling
  packages/orchestrator/internal/sandbox/uffd/handler.go
  packages/orchestrator/internal/sandbox/uffd/mapping/firecracker.go
  packages/orchestrator/internal/sandbox/uffd/mapping/mapping.go
  packages/orchestrator/internal/sandbox/uffd/serve.go
Labels: improvement

#986 Make envd required (it should be already always present)
  packages/api/internal/api/spec.gen.go
  packages/api/internal/api/types.gen.go
  packages/api/internal/handlers/sandbox_get.go
  spec/openapi.yml
  tests/integration/internal/api/models.gen.go
Labels: improvement

#990 Fix pagination query
  packages/api/internal/handlers/sandboxes_list.go
  packages/db/queries/get_snapshots_with_cursor.sql
  packages/db/queries/get_snapshots_with_cursor.sql.go
  tests/integration/internal/tests/api/sandbox_list_test.go
Labels: bug

#886 Create ClickHouse table and queries for sandbox events complete with batcher
  packages/clickhouse/go.mod
  packages/clickhouse/migrations/20250725223340_add_sandbox_events_local.sql
  packages/clickhouse/migrations/20250725223341_add_sandbox_events.sql
  packages/clickhouse/pkg/batcher/bacther_test.go
  packages/clickhouse/pkg/batcher/batcher.go
  packages/clickhouse/pkg/batcher/clickhouse_batcher.go
  packages/clickhouse/pkg/batcher/mock.go
  packages/clickhouse/pkg/batcher/sandbox_events_batcher.go
  packages/clickhouse/pkg/batcher/timer.go
  packages/clickhouse/pkg/clickhouse.go
  packages/clickhouse/pkg/mock.go
  packages/clickhouse/pkg/sandbox_events.go
  packages/cluster/main.tf
  packages/cluster/network/main.tf
  packages/cluster/network/variables.tf
  packages/cluster/variables.tf
  packages/nomad/main.tf
  packages/nomad/orchestrator.hcl
  packages/nomad/template-manager.hcl
  packages/orchestrator/.gitignore
  packages/orchestrator/Dockerfile
  packages/orchestrator/Makefile
  packages/orchestrator/go.mod
  packages/orchestrator/go.sum
  packages/orchestrator/internal/server/main.go
  packages/orchestrator/internal/server/sandboxes.go
  packages/orchestrator/main.go
  packages/shared/pkg/feature-flags/flags.go
Labels: feature, go

#992 Remove old github actions
  .github/workflows/api.yml
  .github/workflows/cluster-disk-image.yml
  .github/workflows/docker-reverse-proxy.yml
  .github/workflows/envd.yml
  .github/workflows/fc-versions.yml
  .github/workflows/orchestrator.yml
  .github/workflows/release.yml
  .github/workflows/template-manager.yml
  .github/workflows/terraform.yml
Labels: improvement

#952 Stop using Nomad Short NodeID in API internals
  packages/api/internal/api/spec.gen.go
  packages/api/internal/api/types.gen.go
  packages/api/internal/cache/instance/sync.go
  packages/api/internal/edge/cluster_instances.go
  packages/api/internal/handlers/admin.go
  packages/api/internal/handlers/sandbox_resume.go
  packages/api/internal/handlers/template_layer_files_upload.go
  packages/api/internal/handlers/template_request_build.go
  packages/api/internal/handlers/template_request_build_v2.go
  packages/api/internal/node/node.go
  packages/api/internal/orchestrator/cache.go
  packages/api/internal/orchestrator/client.go
  packages/api/internal/orchestrator/create_instance.go
  packages/api/internal/orchestrator/keep_alive.go
  packages/api/internal/orchestrator/list_cached_builds.go
  packages/api/internal/orchestrator/list_instances.go
  packages/api/internal/orchestrator/metrics.go
  packages/api/internal/orchestrator/node.go
  packages/api/internal/orchestrator/orchestrator.go
  packages/api/internal/orchestrator/pause_instance.go
  packages/api/internal/orchestrator/update_instance.go
  packages/api/internal/template-manager/template_manager.go
  packages/api/internal/template-manager/template_manager_local.go
  packages/api/internal/template-manager/template_manager_test.go
  packages/api/internal/template-manager/template_status.go
  packages/api/internal/template-manager/upload_template_layer_files.go
  packages/client-proxy/internal/edge/pool/edge-pool.go
  packages/client-proxy/internal/edge/pool/edge.go
  packages/client-proxy/internal/edge/pool/orchestrator-pool.go
  packages/client-proxy/internal/edge/pool/orchestrator.go
  packages/shared/pkg/db/snapshot.go
  packages/shared/pkg/logger/fields.go
  packages/shared/pkg/storage/storage_aws.go
  packages/shared/pkg/telemetry/fields.go
  spec/openapi.yml
Labels: improvement

#991 Report orch metrics
  packages/api/internal/api/spec.gen.go
  packages/api/internal/api/types.gen.go
  packages/api/internal/orchestrator/cache.go
  packages/api/internal/orchestrator/client.go
  packages/api/internal/orchestrator/node.go
  packages/api/internal/orchestrator/orchestrator.go
  packages/client-proxy/internal/edge/handlers/service-discovery-orchestrators.go
  packages/client-proxy/internal/edge/pool/orchestrator.go
  packages/orchestrator/go.mod
  packages/orchestrator/go.sum
  packages/orchestrator/info.proto
  packages/orchestrator/internal/metrics/host.go
  packages/orchestrator/internal/service/service_info.go
  packages/shared/pkg/grpc/orchestrator-info/info.pb.go
  packages/shared/pkg/http/edge/spec.gen.go
  packages/shared/pkg/http/edge/types.gen.go
  spec/openapi-edge.yml
  spec/openapi.yml
  tests/integration/internal/api/models.gen.go
Labels: improvement

#994 Always use actual service instance ID during gRPC call
  packages/api/internal/orchestrator/cache.go
  packages/api/internal/orchestrator/client.go
  packages/api/internal/orchestrator/create_instance.go
  packages/api/internal/orchestrator/node.go
Labels: bug

#982 Add versioning and lifecycle rules to the terraform state bucket
  Makefile
Labels: feature

#996 Improve template permission and not found errors
  packages/api/internal/handlers/template_request_build.go
Labels: improvement

#988 Fix not actual sandbox time when clock sync takes too long
  packages/envd/internal/api/init.go
  packages/envd/internal/host/sync.go
  packages/envd/internal/services/process/start.go
  packages/envd/main.go
  packages/orchestrator/internal/sandbox/fc/process.go
Labels: bug

#1009 Migrate from HCP Vault to Infisical
  .github/actions/deploy-setup/action.yml
  .github/workflows/build-and-upload-job.yml
  .github/workflows/deploy-infra.yml
  .github/workflows/deploy-job.yml
  .gitignore
  Makefile
  scripts/download-prod-env.sh
  scripts/update-prod-env.sh
Labels: improvement

#1017 Fix Infisical export format
  .github/actions/deploy-setup/action.yml
  scripts/download-prod-env.sh
Labels: bug

#1019 Fix paused sandboxes list query performance
  packages/db/migrations/20250820102103_add_snapshots_indexes.sql
Labels: bug

#1020 Validate timestamps for clickhouse
  packages/api/internal/handlers/sandbox_metrics.go
  packages/api/internal/handlers/team_metrics.go
  packages/api/internal/utils/dates.go
  packages/clickhouse/pkg/dates.go
  tests/integration/go.mod
  tests/integration/go.sum
  tests/integration/internal/tests/api/team_metrics_test.go
Labels: improvement

#1011 Fix build caches with constant rootfs path
  packages/orchestrator/internal/sandbox/fc/config.go
  packages/orchestrator/internal/sandbox/fc/script_builder.go
  packages/orchestrator/internal/sandbox/fc/script_builder_test.go
  packages/orchestrator/internal/sandbox/sandbox.go
  packages/orchestrator/internal/sandbox/snapshot.go
  packages/orchestrator/internal/sandbox/template/cache.go
  packages/orchestrator/internal/sandbox/template/local_template.go
  packages/orchestrator/internal/sandbox/template/storage_template.go
  packages/orchestrator/internal/sandbox/template/template.go
  packages/orchestrator/internal/server/sandboxes.go
  packages/orchestrator/internal/template/build/builder.go
  packages/orchestrator/internal/template/build/commands/command.go
  packages/orchestrator/internal/template/build/commands/copy.go
  packages/orchestrator/internal/template/build/commands/env.go
  packages/orchestrator/internal/template/build/commands/executor.go
  packages/orchestrator/internal/template/build/commands/run.go
  packages/orchestrator/internal/template/build/commands/user.go
  packages/orchestrator/internal/template/build/commands/workdir.go
  packages/orchestrator/internal/template/build/layer/function_action.go
  packages/orchestrator/internal/template/build/layer/interfaces.go
  packages/orchestrator/internal/template/build/layer/layer_executor.go
  packages/orchestrator/internal/template/build/phases/base/builder.go
  packages/orchestrator/internal/template/build/phases/finalize/builder.go
  packages/orchestrator/internal/template/build/phases/finalize/configure.go
  packages/orchestrator/internal/template/build/phases/finalize/ready.go
  packages/orchestrator/internal/template/build/phases/phase.go
  packages/orchestrator/internal/template/build/phases/steps/builder.go
  packages/orchestrator/internal/template/build/sandboxtools/command.go
  packages/orchestrator/internal/template/build/storage/cache/cache.go
  packages/orchestrator/internal/template/metadata/template_metadata.go
  packages/shared/pkg/ioutils/write_to_file.go
  packages/shared/pkg/storage/template.go
  packages/shared/pkg/storage/template_build.go
  packages/shared/pkg/storage/template_cache.go
Labels: bug

#1013 Refactor node / orchestrator
  packages/api/internal/cache/instance/instance.go
  packages/api/internal/cache/instance/sync.go
  packages/api/internal/handlers/sandbox_resume.go
  packages/api/internal/node/node.go
  packages/api/internal/orchestrator/admin.go
  packages/api/internal/orchestrator/cache.go
  packages/api/internal/orchestrator/client.go
  packages/api/internal/orchestrator/create_instance.go
  packages/api/internal/orchestrator/keep_alive.go
  packages/api/internal/orchestrator/list_cached_builds.go
  packages/api/internal/orchestrator/list_instances.go
  packages/api/internal/orchestrator/metrics.go
  packages/api/internal/orchestrator/node.go
  packages/api/internal/orchestrator/nodes/builds.go
  packages/api/internal/orchestrator/nodes/client.go
  packages/api/internal/orchestrator/nodes/metadata.go
  packages/api/internal/orchestrator/nodes/metrics.go
  packages/api/internal/orchestrator/nodes/node.go
  packages/api/internal/orchestrator/nodes/placement_metrics.go
  packages/api/internal/orchestrator/nodes/sandboxes.go
  packages/api/internal/orchestrator/nodes/status.go
  packages/api/internal/orchestrator/nodes/sync.go
  packages/api/internal/orchestrator/orchestrator.go
  packages/api/internal/orchestrator/pause_instance.go
  packages/api/internal/orchestrator/placement/config.go
  packages/api/internal/orchestrator/placement/placement.go
  packages/api/internal/orchestrator/placement/placement_least_busy.go
Labels: improvement

#1026 Deprecate all v1 metadata versions
  packages/orchestrator/internal/sandbox/template/storage_template.go
  packages/orchestrator/internal/template/build/storage/cache/cache.go
  packages/orchestrator/internal/template/metadata/template_metadata.go
  packages/orchestrator/internal/template/metadata/template_metadata_test.go
Labels: bug

#1029 Add tests for foreign team access
  .github/actions/start-services/action.yml
  packages/api/internal/cache/templates/cache.go
  packages/api/internal/handlers/store_test.go
  packages/shared/go.mod
  packages/shared/pkg/tests/sign_token.go
  tests/integration/Makefile
  tests/integration/go.mod
  tests/integration/go.sum
  tests/integration/internal/setup/api_client.go
  tests/integration/internal/setup/constants.go
  tests/integration/internal/setup/db_client.go
  tests/integration/internal/tests/api/apikey_test.go
  tests/integration/internal/tests/api/auth/supabase_test.go
  tests/integration/internal/tests/team_test.go
  tests/integration/internal/tests/utils/team.go
  tests/integration/internal/utils/team.go
  tests/integration/internal/utils/user.go
  tests/integration/seed.go
Labels: improvement

#1037 Make sure we are comparing service id, not just node id
  packages/api/internal/edge/cluster_instances.go
Labels: bug

#955 Use Filestore over NFS to speed up and share GCS Object Storage cached slabs
  .env.template
  .github/actions/start-services/action.yml
  .gitignore
  .mockery.yaml
  .terraform.lock.hcl
  Makefile
  main.tf
  packages/cluster-disk-image/main.pkr.hcl
  packages/cluster/filestore/main.tf
  packages/cluster/filestore/output.tf
  packages/cluster/filestore/variables.tf
  packages/cluster/main.tf
  packages/cluster/outputs.tf
  packages/cluster/scripts/start-client.sh
  packages/cluster/variables.tf
  packages/nomad/filestore-cleanup.hcl
  packages/nomad/filestore-cleanup.tf
  packages/nomad/main.tf
  packages/nomad/orchestrator.hcl
  packages/nomad/template-manager.hcl
  packages/nomad/variables.tf
  packages/orchestrator/Dockerfile
  packages/orchestrator/Makefile
  packages/orchestrator/cmd/build-template/main.go
  packages/orchestrator/cmd/clean-nfs-cache/atime_linux.go
  packages/orchestrator/cmd/clean-nfs-cache/atime_osx.go
  packages/orchestrator/cmd/clean-nfs-cache/main.go
  packages/orchestrator/cmd/simulate-headers-merge/main.go
  packages/orchestrator/internal/sandbox/block/chunk.go
  packages/orchestrator/internal/sandbox/template/cache.go
  packages/orchestrator/internal/server/sandboxes.go
  packages/orchestrator/internal/template/build/layer/layer_executor.go
  packages/orchestrator/internal/template/build/writer/postprocessor.go
  packages/orchestrator/main.go
  packages/orchestrator/upload-clean-nfs-cache.sh
  packages/shared/pkg/feature-flags/client.go
  packages/shared/pkg/feature-flags/flags.go
  packages/shared/pkg/storage/storage.go
  packages/shared/pkg/storage/storage_cache.go
  packages/shared/pkg/storage/storage_cache_test.go
  packages/shared/pkg/storage/storage_test.go
  packages/shared/pkg/telemetry/main.go
  tests/integration/internal/tests/api/templates/build_template_test.go
  variables.tf
Labels: improvement

#1039 Enable Filestore API
  packages/init/main.tf
Labels: bug

#1042 Propagate `ErrorObjectNotExist` from AWS and GCP storage providers when calling `.Size()`
  packages/shared/pkg/storage/storage_aws.go
  packages/shared/pkg/storage/storage_cache.go
  packages/shared/pkg/storage/storage_google.go
Labels: bug

#1043 Missing request metadata during node registration
  packages/api/internal/orchestrator/nodemanager/node.go
Labels: bug

#1040 Propagate service metadata to OTEL
  packages/api/Makefile
  packages/api/internal/metrics/team.go
  packages/api/main.go
  packages/client-proxy/internal/consts.go
  packages/client-proxy/main.go
  packages/nomad/api.hcl
  packages/orchestrator/internal/metrics/sandboxes.go
  packages/orchestrator/internal/sandbox/network/pool.go
  packages/orchestrator/internal/sandbox/network/storage.go
  packages/orchestrator/internal/sandbox/network/storage_kv.go
  packages/orchestrator/internal/service/info.go
  packages/orchestrator/internal/service/service.go
  packages/orchestrator/main.go
  packages/shared/pkg/env/env.go
  packages/shared/pkg/telemetry/config.go
  packages/shared/pkg/telemetry/logs.go
  packages/shared/pkg/telemetry/main.go
  packages/shared/pkg/telemetry/metrics.go
  packages/shared/pkg/telemetry/traces.go
Labels: improvement

#1047 Do not cache when building a template, only when starting a sandbox
  packages/orchestrator/internal/sandbox/template/cache.go
  packages/orchestrator/internal/server/sandboxes.go
  packages/orchestrator/internal/template/build/layer/create_sandbox.go
  packages/orchestrator/internal/template/build/layer/layer_executor.go
  packages/orchestrator/internal/template/build/layer/resume_sandbox.go
  packages/shared/pkg/storage/storage_cache.go
Labels: feature

#1058 Cache periodic tests dependencies
  .github/workflows/periodic-test.yml
  tests/periodic-test/cli-logs.ts
  tests/periodic-test/create-file.ts
  tests/periodic-test/deno.json
  tests/periodic-test/deno.lock
  tests/periodic-test/internet-works.ts
  tests/periodic-test/run-code.ts
  tests/periodic-test/snapshot-and-resume.ts
  tests/periodic-test/time-is-synchronized/deno.json
  tests/periodic-test/time-is-synchronized/index.ts
Labels: improvement

#1057 Enforce max concurrent sandboxes per node in the orchestrator
  packages/api/internal/orchestrator/placement/placement.go
  packages/api/internal/orchestrator/placement/placement_test.go
  packages/orchestrator/internal/server/main.go
  packages/orchestrator/internal/server/sandboxes.go
  tests/integration/internal/tests/api/kill_test.go
Labels: improvement

#1053 Add the tparallel linter
  .github/workflows/lint.yml
  .github/workflows/pr-tests.yml
  .golangci.yml
  packages/envd/internal/services/filesystem/dir_test.go
  packages/envd/internal/services/filesystem/move_test.go
  packages/envd/internal/services/filesystem/stat_test.go
  packages/envd/internal/services/filesystem/utils_test.go
  tests/integration/internal/tests/api/sandbox_internet_test.go
  tests/integration/internal/tests/envd/localhost_bind_test.go
Labels: improvement

#1072 Nodes sync race condition
  packages/api/internal/edge/cluster.go
  packages/api/internal/orchestrator/cache.go
  packages/api/internal/orchestrator/nodemanager/metadata.go
  packages/api/internal/orchestrator/nodemanager/node.go
  packages/api/internal/orchestrator/nodemanager/sync.go
  packages/shared/pkg/synchronization/synchronization.go
Labels: bug

#1030 feat: allow passing login to Docker registries
  packages/api/internal/api/spec.gen.go
  packages/api/internal/api/types.gen.go
  packages/api/internal/handlers/template_start_build.go
  packages/api/internal/handlers/template_start_build_v2.go
  packages/api/internal/template-manager/create_template.go
  packages/orchestrator/Makefile
  packages/orchestrator/go.mod
  packages/orchestrator/internal/template/build/config/config.go
  packages/orchestrator/internal/template/build/core/oci/auth/auth.go
  packages/orchestrator/internal/template/build/core/oci/auth/aws.go
  packages/orchestrator/internal/template/build/core/oci/auth/gcp.go
  packages/orchestrator/internal/template/build/core/oci/auth/general.go
  packages/orchestrator/internal/template/build/core/oci/oci.go
  packages/orchestrator/internal/template/build/core/oci/oci_test.go
  packages/orchestrator/internal/template/build/core/rootfs/rootfs.go
  packages/orchestrator/internal/template/server/create_template.go
  packages/orchestrator/template-manager.proto
  packages/orchestrator/test.Dockerfile
  packages/shared/pkg/grpc/template-manager/template-manager.pb.go
  spec/openapi.yml
  tests/integration/internal/api/models.gen.go
Labels: feature

#1076 Use context.WithoutCancel for fetch calls to prevent cancellation
  packages/orchestrator/internal/sandbox/template/cache.go
Labels: bug

#1080 Add service instance id to `/nodes` endpoints
  packages/api/internal/api/api.gen.go
  packages/api/internal/api/spec.gen.go
  packages/api/internal/api/types.gen.go
  packages/api/internal/handlers/admin.go
  packages/api/internal/orchestrator/admin.go
  spec/openapi.yml
  tests/integration/internal/api/client.gen.go
  tests/integration/internal/api/models.gen.go
Labels: improvement

#1082 Fixed issue when comparing empty metadata jsonb with NULL column
  packages/db/queries/get_snapshots_with_cursor.sql
  packages/db/queries/get_snapshots_with_cursor.sql.go
  tests/integration/internal/tests/api/sandbox_list_test.go
  tests/integration/internal/utils/sandbox.go
Labels: bug

#1087 Increase hard command timeout for template building
  packages/orchestrator/internal/template/build/sandboxtools/command.go
Labels: bug

#1088 Fix UFFD panic in template build
  packages/orchestrator/internal/sandbox/block/empty.go
  packages/orchestrator/internal/sandbox/template/local_template.go
  packages/orchestrator/internal/sandbox/template/mask_template.go
  packages/orchestrator/internal/sandbox/template/storage_template.go
  packages/orchestrator/internal/sandbox/template/template.go
  packages/orchestrator/internal/template/build/core/memory/memory.go
  packages/orchestrator/internal/template/build/layer/create_sandbox.go
  packages/orchestrator/internal/template/build/phases/base/files.go
Labels: bug
