Repository e2b-dev/infra, pull requests merged in 2025-01, with the labels that each got.

#229 Filter out snapshots from templates API endpoint
  packages/shared/pkg/db/envs.go
Labels: bug

#227 Fix is not found error
  packages/shared/pkg/db/snapshot.go
Labels: bug

#196 Add multi-file write support
  packages/envd/internal/api/upload.go
  packages/envd/internal/utils/multipart.go
  packages/envd/main.go
Labels: feature

#236 Set default IS_SANDBOX env var upon envd init
  packages/envd/README.md
  packages/envd/internal/api/init.go
  packages/envd/main.go
Labels: improvement

#230 Fix snapshot mapping merge bug
  packages/api/.gitignore
  packages/orchestrator/cmd/inspect-header/main.go
  packages/orchestrator/cmd/simulate-headers-merge/main.go
  packages/orchestrator/go.mod
  packages/shared/go.mod
  packages/shared/go.sum
  packages/shared/pkg/storage/header/inspect.go
  packages/shared/pkg/storage/header/mapping.go
  packages/shared/pkg/storage/header/mapping_test.go
Labels: bug

#239 Add missing DNS request token
  packages/cluster/scripts/start-api.sh
  packages/cluster/scripts/start-client.sh
  packages/cluster/server/main.tf
Labels: bug

#238 Handle failed connection to template manager during build
  packages/api/internal/handlers/template_start_build.go
  packages/api/internal/template-manager/create_template.go
Labels: bug

#233 Add watch dir recursive option
  go.work.sum
  packages/envd/go.mod
  packages/envd/internal/services/filesystem/watch.go
  packages/envd/internal/services/filesystem/watch_sync.go
  packages/envd/internal/services/spec/filesystem/filesystem.pb.go
  packages/envd/internal/utils/rfsnotify.go
  packages/envd/main.go
  packages/envd/spec/filesystem/filesystem.proto
Labels: feature

#240 Add logs for pulling docker image during build
  packages/template-manager/internal/build/rootfs.go
Labels: improvement

#231 Show useful 502 message for not running/existent sandbox
  packages/api/internal/dns/server.go
  packages/api/internal/orchestrator/orchestrator.go
  packages/nomad/proxies/client.conf
  packages/orchestrator/cmd/mock-sandbox/mock.go
  packages/orchestrator/cmd/mock-snapshot/mock.go
  packages/orchestrator/internal/dns/server.go
  packages/orchestrator/internal/sandbox/sandbox.go
  packages/orchestrator/internal/server/main.go
Labels: improvement

#244 Don't cache envd
  packages/cluster/scripts/start-client.sh
Labels: improvement

#243 Return correct errors for not found template
  packages/api/internal/cache/templates/cache.go
  packages/api/internal/handlers/sandbox_create.go
  packages/shared/pkg/db/envs.go
Labels: bug, improvement

#241 Stop waiting for complete sandbox stop during pausing
  packages/orchestrator/internal/sandbox/rootfs/cow.go
  packages/orchestrator/internal/sandbox/sandbox.go
  packages/orchestrator/internal/server/sandboxes.go
Labels: bug, improvement

#242 Add metrics to allow us set up alerts for error rate and slowing requests
  packages/api/main.go
  packages/shared/pkg/gin_utils/middleware/otel/metrics/config.go
  packages/shared/pkg/gin_utils/middleware/otel/metrics/middleware.go
  packages/shared/pkg/gin_utils/middleware/otel/metrics/otelrecorder.go
Labels: improvement

#235 Add filtering option for listing sandboxes
  packages/api/internal/api/api.gen.go
  packages/api/internal/api/spec.gen.go
  packages/api/internal/api/types.gen.go
  packages/api/internal/handlers/sandbox_get.go
  packages/api/internal/handlers/sandboxes_list.go
  packages/api/internal/handlers/teams.go
  spec/openapi.yml
Labels: feature

#251 Improve self-hosted GCP guide
  .env.template
  self-host.md
Labels: docs

#254 Add condition to instant replace the orchestrator on staging
  packages/nomad/main.tf
  packages/nomad/orchestrator.hcl
Labels: improvement

#248 shared(api): context infrastructure plumbing for shared packages
  packages/api/main.go
  packages/orchestrator/cmd/mock-snapshot/mock.go
  packages/orchestrator/main.go
  packages/shared/pkg/db/client.go
  packages/shared/pkg/telemetry/otel.go
  packages/template-manager/main.go
Labels: improvement

#216 Periodically capture resource metrics for every sandbox
  packages/api/internal/api/api.gen.go
  packages/api/internal/api/spec.gen.go
  packages/api/internal/api/types.gen.go
  packages/api/internal/handlers/sandbox_metrics.go
  packages/envd/internal/host/metrics.go
  packages/envd/main.go
  packages/envd/spec/envd.yaml
  packages/nomad/logs-collector.hcl
  packages/orchestrator/internal/sandbox/checks.go
  packages/orchestrator/internal/sandbox/metrics.go
  packages/orchestrator/internal/server/sandboxes.go
  packages/shared/pkg/logs/logger.go
  spec/openapi.yml
Labels: feature

#255 Fix mmap flush to the filesystem
  packages/orchestrator/internal/sandbox/block/cache.go
Labels: bug

#250 Prevent closed block cache usage
  packages/orchestrator/internal/sandbox/block/cache.go
Labels: improvement
