Repository e2b-dev/infra, pull requests merged in 2025-07, with the labels that each got.

#837 Fix local template manager deadlock
  packages/api/internal/template-manager/template_manager.go
Labels: bug

#834 Update metadata during sync
  packages/api/internal/orchestrator/cache.go
  packages/api/internal/orchestrator/client.go
  packages/api/internal/orchestrator/metrics.go
  packages/api/internal/orchestrator/node.go
Labels: bug

#841 Handle Unexpected EOF for ReadAt in AWS S3 storage provider
  packages/shared/pkg/storage/storage_aws.go
Labels: bug

#845 Fix Redis in cluster mode
  packages/nomad/api.hcl
  packages/nomad/edge.hcl
  packages/nomad/main.tf
Labels: bug

#851 Update dotenv for client cluster size
  .env.template
Labels: bug

#838 Update self-host.md - small update to GCP requirements
  self-host.md
Labels: docs

#862 Fix edge pool race condition
  packages/api/internal/edge/pool.go
Labels: bug

#867 Add sandbox create metrics
  packages/api/internal/api/spec.gen.go
  packages/api/internal/api/types.gen.go
  packages/api/internal/orchestrator/create_instance.go
  packages/api/internal/orchestrator/metrics.go
  packages/api/internal/orchestrator/node.go
  packages/api/internal/orchestrator/orchestrator.go
  packages/shared/pkg/telemetry/meters.go
  spec/openapi.yml
Labels: improvement

#861 Add sandbox metrics endpoint
  packages/api/go.mod
  packages/api/go.sum
  packages/api/internal/api/api.gen.go
  packages/api/internal/api/spec.gen.go
  packages/api/internal/api/types.gen.go
  packages/api/internal/handlers/sandbox_metrics.go
  packages/clickhouse/go.mod
  packages/clickhouse/go.sum
  packages/clickhouse/pkg/clickhouse.go
  packages/clickhouse/pkg/metrics.go
  packages/clickhouse/pkg/mock.go
  packages/client-proxy/go.mod
  packages/client-proxy/go.sum
  packages/db/go.mod
  packages/db/go.sum
  packages/docker-reverse-proxy/go.mod
  packages/docker-reverse-proxy/go.sum
  packages/envd/go.mod
  packages/envd/go.sum
  packages/orchestrator/go.mod
  packages/orchestrator/go.sum
  packages/shared/go.mod
  packages/shared/go.sum
  spec/openapi.yml
  tests/integration/go.mod
  tests/integration/go.sum
Labels: feature

#876 Increase the timeout to 1 hour and use the correct context
  packages/api/internal/template-manager/template_status.go
Labels: bug

#878 Traffic proxy working without client part
  packages/orchestrator/internal/proxy/proxy.go
  packages/shared/pkg/proxy/host.go
  packages/shared/pkg/proxy/host_test.go
Labels: feature

#879 Refactor sandbox metrics list
  packages/api/internal/api/api.gen.go
  packages/api/internal/api/spec.gen.go
  packages/api/internal/api/types.gen.go
  packages/api/internal/handlers/sandboxes_list_metrics.go
  spec/openapi.yml
Labels: improvement

#882 Add OTEL collector metrics
  packages/nomad/configs/otel-collector.yaml
  packages/nomad/otel-collector.hcl
Labels: improvement

#883 Fix envd resolving path
  packages/envd/go.mod
  packages/envd/internal/services/filesystem/dir.go
  packages/envd/internal/services/filesystem/dir_test.go
  packages/envd/main.go
  tests/integration/internal/tests/envd/filesystem_test.go
Labels: bug

#884 Restrict template cache with cluster ID
  packages/api/internal/cache/templates/cache.go
  packages/api/internal/handlers/sandbox_create.go
Labels: bug

#887 Clickhouse - Add dedicated sandbox metrics table
  packages/clickhouse/Makefile
  packages/clickhouse/migrations/20250521131545_add_metrics_local.sql
  packages/clickhouse/migrations/20250717135224_sandbox_metrics.sql
  packages/clickhouse/pkg/metrics.go
Labels: improvement

#880 Improve build logs with structured messages
  packages/api/go.mod
  packages/api/go.sum
  packages/api/internal/api/api.gen.go
  packages/api/internal/api/spec.gen.go
  packages/api/internal/api/types.gen.go
  packages/api/internal/handlers/template_build_status.go
  packages/api/internal/template-manager/build_client.go
  packages/api/internal/template-manager/logs/edge_provider.go
  packages/api/internal/template-manager/logs/loki_provider.go
  packages/api/internal/template-manager/logs/provider.go
  packages/api/internal/template-manager/logs/template_manager_provider.go
  packages/client-proxy/go.mod
  packages/client-proxy/go.sum
  packages/client-proxy/internal/edge/handlers/template-build-logs.go
  packages/client-proxy/internal/edge/logger-provider/provider.go
  packages/client-proxy/internal/edge/logger-provider/provider_loki.go
  packages/db/go.mod
  packages/envd/go.mod
  packages/orchestrator/cmd/build-template/main.go
  packages/orchestrator/go.mod
  packages/orchestrator/go.sum
  packages/orchestrator/internal/template/build/apply_command.go
  packages/orchestrator/internal/template/build/build_layer.go
  packages/orchestrator/internal/template/build/builder.go
  packages/orchestrator/internal/template/build/configure_command.go
  packages/orchestrator/internal/template/build/oci/oci.go
  packages/orchestrator/internal/template/build/oci/oci_test.go
  packages/orchestrator/internal/template/build/provision.go
  packages/orchestrator/internal/template/build/ready_command.go
  packages/orchestrator/internal/template/build/rootfs/rootfs.go
  packages/orchestrator/internal/template/build/sandboxtools/command.go
  packages/orchestrator/internal/template/build/writer/postprocessor.go
  packages/orchestrator/internal/template/build/writer/postprocessor_test.go
  packages/orchestrator/internal/template/build/writer/writer.go
  packages/orchestrator/internal/template/cache/build_cache.go
  packages/orchestrator/internal/template/cache/safe_buffer.go
  packages/orchestrator/internal/template/server/create_template.go
  packages/orchestrator/internal/template/server/main.go
  packages/orchestrator/internal/template/server/template_status.go
  packages/orchestrator/template-manager.proto
  packages/shared/go.mod
  packages/shared/go.sum
  packages/shared/pkg/grpc/template-manager/template-manager.pb.go
  packages/shared/pkg/http/edge/api.gen.go
  packages/shared/pkg/http/edge/client.gen.go
  packages/shared/pkg/http/edge/spec.gen.go
  packages/shared/pkg/http/edge/types.gen.go
  packages/shared/pkg/logs/logs.go
  packages/shared/pkg/logs/loki.go
  spec/openapi-edge.yml
  spec/openapi.yml
  tests/integration/go.mod
Labels: improvement

#895 Add disk usage metrics
  packages/api/internal/api/spec.gen.go
  packages/api/internal/api/types.gen.go
  packages/api/internal/handlers/sandbox_create.go
  packages/api/internal/handlers/sandbox_metrics.go
  packages/api/internal/handlers/sandboxes_list_metrics.go
  packages/clickhouse/pkg/metrics.go
  packages/envd/go.mod
  packages/envd/internal/host/metrics.go
  packages/envd/main.go
  packages/orchestrator/internal/metrics/sandboxes.go
  packages/orchestrator/internal/sandbox/metrics.go
  packages/shared/pkg/telemetry/meters.go
  packages/shared/pkg/utils/version.go
  packages/shared/pkg/utils/version_test.go
  spec/openapi.yml
Labels: improvement

#896 Fix sandbox cleanup on timeout error
  packages/orchestrator/internal/server/sandboxes.go
Labels: bug

#901 Fix race condition in the FC process shutdown and cleanup
  packages/orchestrator/internal/sandbox/fc/process.go
  packages/orchestrator/internal/sandbox/sandbox.go
  packages/orchestrator/internal/server/sandboxes.go
Labels: bug, improvement

#902 Fix api enum values
  packages/api/internal/api/spec.gen.go
  packages/api/internal/api/types.gen.go
  spec/openapi.yml
Labels: bug

#881 Authenticate using the team api key for template builds
  packages/api/internal/api/api.gen.go
  packages/api/internal/api/spec.gen.go
  packages/api/internal/api/types.gen.go
  packages/api/internal/auth/middleware.go
  packages/api/internal/cache/auth/cache.go
  packages/api/internal/db/apikeys.go
  packages/api/internal/db/user.go
  packages/api/internal/handlers/store.go
  packages/api/internal/handlers/template_build_status.go
  packages/api/internal/handlers/template_layer_files_upload.go
  packages/api/internal/handlers/template_request_build.go
  packages/api/internal/handlers/template_request_build_v2.go
  packages/api/internal/handlers/template_start_build.go
  packages/api/internal/handlers/template_start_build_v2.go
  packages/api/internal/utils/error.go
  packages/db/queries/get_team_tier_by_api_key.sql
  packages/db/queries/get_team_tier_by_api_key.sql.go
  packages/db/queries/get_team_tier_by_team_and_user.sql
  packages/db/queries/get_team_tier_by_team_and_user.sql.go
  packages/db/queries/get_template_build.sql
  packages/db/queries/get_template_build.sql.go
  packages/db/queries/get_template_by_id.sql
  packages/db/queries/get_template_by_id.sql.go
  packages/shared/pkg/db/apiKeys.go
  packages/shared/pkg/db/auth.go
  spec/openapi.yml
  tests/integration/internal/tests/api/kill_test.go
Labels: feature

#910 Docs: Remove dashboard domain setting instructions from self-host documentation
  self-host.md
Labels: docs

#900 Limit resource usage and parallelism of `gcloud` when uploading snapshots to reduce `EOF` errors
  packages/api/go.mod
  packages/api/go.sum
  packages/api/internal/handlers/sandbox_metrics.go
  packages/api/internal/handlers/sandboxes_list_metrics.go
  packages/orchestrator/cmd/build-template/main.go
  packages/orchestrator/cmd/inspect-data/main.go
  packages/orchestrator/cmd/inspect-header/main.go
  packages/orchestrator/cmd/simulate-headers-merge/main.go
  packages/orchestrator/go.mod
  packages/orchestrator/go.sum
  packages/orchestrator/internal/sandbox/template/cache.go
  packages/orchestrator/internal/server/main.go
  packages/orchestrator/internal/server/sandboxes.go
  packages/orchestrator/internal/template/server/main.go
  packages/orchestrator/main.go
  packages/shared/go.mod
  packages/shared/go.sum
  packages/shared/pkg/feature-flags/client.go
  packages/shared/pkg/feature-flags/client_test.go
  packages/shared/pkg/feature-flags/flags.go
  packages/shared/pkg/limit/gcloud.go
  packages/shared/pkg/limit/limiter.go
  packages/shared/pkg/limit/upload.go
  packages/shared/pkg/storage/storage.go
  packages/shared/pkg/storage/storage_google.go
  packages/shared/pkg/utils/resizable_semaphore.go
  packages/shared/pkg/utils/resizable_semaphore_test.go
Labels: bug, improvement

#847 Block changes from affecting the broken python sdk
  .mockery.yaml
  packages/envd/go.mod
  packages/envd/go.sum
  packages/envd/internal/services/filesystem/service.go
  packages/envd/internal/services/filesystem/watch_sync.go
  packages/envd/internal/services/legacy/buf.gen.yaml
  packages/envd/internal/services/legacy/conversion.go
  packages/envd/internal/services/legacy/conversion_test.go
  packages/envd/internal/services/legacy/interceptor.go
  packages/envd/internal/services/legacy/interceptor_test.go
  packages/envd/internal/services/legacy/legacyfilesystem.pb.go
  packages/envd/internal/services/legacy/legacyfilesystem.proto
  packages/envd/internal/services/legacy/legacyprocess.pb.go
  packages/envd/internal/services/legacy/legacyprocess.proto
  packages/envd/internal/services/legacy/mocks_test.go
  packages/envd/internal/services/legacy/readme.md
  packages/envd/internal/services/legacy/stream.go
Labels: bug, improvement

#892 Clickhouse - Use otel table only for routing
  packages/clickhouse/migrations/20250721084412_routing.sql
Labels: improvement

#908 Allow specifying custom user for the RUN
  packages/orchestrator/internal/template/build/command/run.go
Labels: improvement

#905 Remove template manager health status
  packages/api/internal/edge/cluster.go
  packages/api/internal/edge/cluster_instances.go
  packages/api/internal/orchestrator/client.go
  packages/api/internal/template-manager/template_manager.go
  packages/api/internal/template-manager/template_manager_local.go
  packages/client-proxy/internal/edge/handlers/service-discovery-node-drain.go
  packages/client-proxy/internal/edge/pool/orchestrator-pool.go
  packages/client-proxy/internal/edge/pool/orchestrator.go
  packages/orchestrator/info.proto
  packages/orchestrator/internal/healthcheck/healthcheck.go
  packages/orchestrator/internal/service/info.go
  packages/orchestrator/internal/template/server/create_template.go
  packages/orchestrator/internal/template/server/health_status.go
  packages/orchestrator/internal/template/server/main.go
  packages/orchestrator/main.go
  packages/orchestrator/template-manager.proto
  packages/shared/pkg/grpc/orchestrator-info/info.pb.go
  packages/shared/pkg/grpc/template-manager/template-manager.pb.go
  packages/shared/pkg/grpc/template-manager/template-manager_grpc.pb.go
Labels: improvement

#913 Added fields to envd stat/list method response (#745)
  packages/envd/internal/services/filesystem/dir.go
  packages/envd/internal/services/filesystem/move.go
  packages/envd/internal/services/filesystem/stat.go
  packages/envd/internal/services/filesystem/utils.go
  packages/envd/internal/services/filesystem/utils_test.go
  packages/envd/internal/services/legacy/conversion_test.go
  packages/envd/internal/services/spec/filesystem/filesystem.pb.go
  packages/envd/main.go
  packages/envd/spec/filesystem/filesystem.proto
  packages/shared/pkg/grpc/envd/filesystem/filesystem.pb.go
  tests/integration/internal/api/client.gen.go
  tests/integration/internal/api/models.gen.go
  tests/integration/internal/tests/envd/auth_test.go
  tests/integration/internal/tests/envd/filesystem_test.go
  tests/integration/internal/utils/filesystem.go
Labels: improvement, feature, go

#921 Allow to block network from SDK (API part)
  packages/api/internal/api/spec.gen.go
  packages/api/internal/api/types.gen.go
  packages/api/internal/cache/instance/instance.go
  packages/api/internal/handlers/sandbox.go
  packages/api/internal/handlers/sandbox_create.go
  packages/api/internal/handlers/sandbox_resume.go
  packages/api/internal/orchestrator/create_instance.go
  packages/api/internal/orchestrator/list_instances.go
  packages/api/internal/orchestrator/pause_instance.go
  packages/db/migrations/20250728085406_add_create_network_flag.sql
  packages/db/queries/get_last_snapshot.sql.go
  packages/db/queries/get_snapshots_with_cursor.sql.go
  packages/db/queries/models.go
  packages/orchestrator/internal/sandbox/sandbox.go
  packages/orchestrator/internal/server/sandboxes.go
  packages/orchestrator/internal/template/build/build_layer.go
  packages/orchestrator/internal/template/build/builder.go
  packages/orchestrator/internal/template/build/provision.go
  packages/orchestrator/orchestrator.proto
  packages/shared/pkg/db/snapshot.go
  packages/shared/pkg/grpc/orchestrator/orchestrator.pb.go
  packages/shared/pkg/models/migrate/schema.go
  packages/shared/pkg/models/mutation.go
  packages/shared/pkg/models/snapshot.go
  packages/shared/pkg/models/snapshot/snapshot.go
  packages/shared/pkg/models/snapshot/where.go
  packages/shared/pkg/models/snapshot_create.go
  packages/shared/pkg/models/snapshot_update.go
  packages/shared/pkg/schema/snapshots.go
  spec/openapi.yml
  tests/integration/internal/api/models.gen.go
  tests/integration/internal/tests/api/sandbox_internet_test.go
  tests/integration/internal/utils/process.go
Labels: feature

#924 Fix envd symlink resolution
  packages/envd/internal/services/filesystem/dir.go
  packages/envd/internal/services/filesystem/move.go
  packages/envd/internal/services/filesystem/stat.go
  packages/envd/internal/services/filesystem/stat_test.go
  packages/envd/internal/services/filesystem/utils.go
  packages/envd/internal/services/filesystem/utils_test.go
  packages/envd/main.go
Labels: bug

#915 Add metrics to memory serving processes
  .env.template
  packages/orchestrator/cmd/build-template/main.go
  packages/orchestrator/internal/sandbox/block/cache.go
  packages/orchestrator/internal/sandbox/block/chunk.go
  packages/orchestrator/internal/sandbox/block/metrics/main.go
  packages/orchestrator/internal/sandbox/build/build.go
  packages/orchestrator/internal/sandbox/build/storage_diff.go
  packages/orchestrator/internal/sandbox/template/cache.go
  packages/orchestrator/internal/sandbox/template/storage.go
  packages/orchestrator/internal/sandbox/template/storage_template.go
  packages/orchestrator/internal/sandbox/uffd/serve.go
  packages/orchestrator/main.go
  packages/shared/pkg/storage/header/diff.go
  packages/shared/pkg/storage/header/diff_test.go
Labels: improvement

#926 Increase envd timeout
  Makefile
  main.tf
  packages/nomad/main.tf
  packages/nomad/orchestrator.hcl
  packages/nomad/variables.tf
  variables.tf
Labels: bug

#934 Ensure workdir exists before running a command
  packages/envd/internal/services/process/handler/handler.go
  packages/envd/main.go
  tests/integration/internal/tests/envd/process_test.go
  tests/integration/internal/utils/process.go
Labels: bug

#936 Update fsnotify
  packages/envd/go.mod
  packages/envd/go.sum
  packages/envd/main.go
Labels: dependencies

#938 Add user agent header
  packages/api/main.go
Labels: bug
