Repository e2b-dev/infra, pull requests merged in 2025-10, with the labels that each got.

#1278 Move docker reverse proxy to api node pool
  iac/provider-gcp/nomad/main.tf
Labels: improvement

#1265 Dynamically customizable timeout for envd init
  packages/orchestrator/internal/metrics/sandboxes.go
  packages/orchestrator/internal/sandbox/envd.go
  packages/orchestrator/internal/sandbox/sandbox.go
  packages/orchestrator/internal/template/build/phases/base/builder.go
  packages/orchestrator/internal/template/build/phases/finalize/builder.go
  packages/orchestrator/internal/template/build/phases/steps/builder.go
  packages/shared/pkg/feature-flags/flags.go
  packages/shared/pkg/logger/fields.go
  packages/shared/pkg/telemetry/fields.go
  packages/shared/pkg/telemetry/meters.go
Labels: improvement

#1283 Update the time for each request
  packages/orchestrator/internal/sandbox/envd.go
Labels: improvement

#1286 Improve test time is synced
  tests/periodic-test/time-is-synchronized/index.ts
Labels: bug

#1287 Add dns resolution logs and handle error correctly
  packages/client-proxy/internal/proxy/proxy.go
  packages/shared/pkg/proxy/handler.go
Labels: bug, improvement

#1288 Enable journal and metadata csum ext4 flags
  packages/orchestrator/internal/template/build/core/filesystem/ext4.go
  packages/orchestrator/internal/template/build/storage/cache/cache.go
Labels: improvement

#1289 fix: template build panic handling
  packages/orchestrator/internal/template/build/builder.go
  packages/orchestrator/internal/template/server/create_template.go
Labels: bug

#1290 Decrease the test reruns to 1
  tests/integration/Makefile
  tests/integration/internal/tests/api/sandboxes/sandbox_internet_test.go
Labels: improvement

#1292 Fix summary log
  packages/orchestrator/cmd/clean-nfs-cache/main.go
Labels: bug

#1294 Client proxy - Fix config name
  iac/provider-gcp/Makefile
Labels: bug

#1271 Simplify sandbox store
  packages/api/internal/handlers/sandboxes_list.go
  packages/api/internal/orchestrator/analytics.go
  packages/api/internal/orchestrator/evictor/evict.go
  packages/api/internal/orchestrator/keep_alive.go
  packages/api/internal/orchestrator/list_instances.go
  packages/api/internal/sandbox/errors.go
  packages/api/internal/sandbox/store.go
  packages/api/internal/sandbox/store/memory/filters.go
  packages/api/internal/sandbox/store/memory/operations.go
  packages/api/internal/sandbox/store/memory/sandbox.go
Labels: improvement

#1301 Edge - Fix defer callback
  packages/client-proxy/internal/edge-pass-through/proxy.go
Labels: bug

#1304 Sandbox Store- Explicitly require the state
  packages/api/internal/handlers/sandboxes_list.go
  packages/api/internal/metrics/team.go
  packages/api/internal/orchestrator/admin.go
  packages/api/internal/orchestrator/analytics.go
  packages/api/internal/orchestrator/evictor/evict.go
  packages/api/internal/orchestrator/list_instances.go
  packages/api/internal/orchestrator/orchestrator.go
  packages/api/internal/sandbox/store.go
  packages/api/internal/sandbox/store/memory/filters.go
  packages/api/internal/sandbox/store/memory/filters_test.go
  packages/api/internal/sandbox/store/memory/operations.go
Labels: bug

#1309 Handle non running already paused sandbox
  packages/api/internal/handlers/sandbox_pause.go
  tests/integration/internal/tests/api/sandboxes/sandbox_pause_test.go
Labels: bug

#1310 Fix flaky sandbox metrics test
  tests/integration/internal/tests/api/metrics/sandbox_list_metrics_test.go
Labels: bug

#1323 Run http logs exporter only once and async
  packages/envd/internal/logs/exporter/exporter.go
  packages/envd/main.go
Labels: bug
