Repository e2b-dev/infra, pull requests merged in 2025-03, with the labels that each got.

#352 Fix build cluster platform
  packages/cluster/build-cluster/main.tf
  packages/envd/internal/host/sync.go
Labels: bug

#349 Add proper handling for UFFD EAGAIN error
  packages/orchestrator/internal/sandbox/uffd/serve.go
Labels: bug

#311 Increase ram allocation for select templates
  packages/template-manager/internal/build/snapshot_linux.go
Labels: feature

#356 Remove outdated info in Dev.md
  DEV.md
Labels: improvement

#362 Reenable rate limiting
  packages/api/internal/handlers/sandbox.go
  packages/api/internal/handlers/sandbox_create.go
  packages/api/internal/handlers/sandbox_resume.go
  packages/api/internal/orchestrator/create_instance.go
Labels: bug

#367 Fix sandbox logs timestamps
  packages/nomad/logs-collector.hcl
  packages/shared/pkg/logger/logger.go
Labels: bug

#366 Set sandbox healthy status to true by default
  packages/orchestrator/internal/sandbox/checks.go
  packages/orchestrator/internal/sandbox/sandbox.go
Labels: bug

#372 Remove bravo from periodic tests
  .github/workflows/periodic-test.yml
Labels: improvement

#369 remove unused compiler option from deno.json
  tests/periodic-test/build-template/deno.json
  tests/periodic-test/deno.json
Labels: improvement

#353 Return correct status code for refresh/timeout
  packages/api/internal/cache/instance/sync.go
  packages/api/internal/handlers/sandbox_refresh.go
  packages/api/internal/handlers/sandbox_timeout.go
  packages/api/internal/orchestrator/keep_alive.go
Labels: bug

#373 Add debug logs to understand more pause/sync issue
  packages/api/internal/cache/instance/instance.go
  packages/api/internal/cache/instance/operations.go
  packages/api/internal/handlers/sandbox_resume.go
  packages/api/internal/orchestrator/cache.go
  packages/api/internal/orchestrator/delete_instance.go
Labels: improvement

#360 Test logging from e2b cli is operating normally
  .github/workflows/periodic-test.yml
  tests/periodic-test/cli-logs.ts
Labels: improvement

#377 Fix break in initial health loop in API
  packages/api/internal/handlers/store.go
Labels: bug

#330 Share transport among reverse proxies
  packages/api/internal/orchestrator/delete_instance.go
  packages/client-proxy/main.go
  packages/orchestrator/internal/sandbox/nbd/dispatch.go
  packages/shared/pkg/logger/exporter.go
  packages/shared/pkg/meters/main.go
  packages/shared/pkg/utils/set_once.go
  packages/template-manager/internal/build/network_linux.go
Labels: improvement

#375 Test logging from e2b cli is operating normally
  .github/workflows/periodic-test.yml
  tests/periodic-test/cli-logs.ts
Labels: improvement

#384 Fix cache eviction and sync node synchronization
  packages/api/internal/cache/instance/lifecycle_cache.go
  packages/api/internal/cache/instance/lifecycle_cache_test.go
  packages/api/internal/cache/instance/operations.go
Labels: bug

#385 Add indexes to DB for frequently used columns
  packages/shared/migrations/20250306105106.sql
Labels: improvement

#355 Remove template logs from API cache
  packages/api/internal/handlers/template_build_logs.go
  packages/api/internal/template-manager/create_template.go
  packages/nomad/logs-collector.hcl
  packages/template-manager/internal/build/rootfs.go
  packages/template-manager/internal/build/rootfs_test.go
  packages/template-manager/internal/build/writer/writer.go
  packages/template-manager/internal/server/create_template.go
  packages/template-manager/internal/server/main.go
  packages/template-manager/main.go
Labels: improvement

#387 Fix nil dereference
  packages/orchestrator/internal/server/sandboxes.go
Labels: bug

#388 Make envd timeout a variable
  .github/actions/start-services/action.yml
  packages/orchestrator/Makefile
  packages/orchestrator/internal/sandbox/sandbox.go
Labels: improvement

#390 Handle error when creating transaction
  packages/shared/pkg/db/snapshot.go
Labels: bug

#393 Not all logs sandbox lifecycle are present
  packages/api/internal/handlers/sandbox_logs.go
  packages/api/internal/handlers/sandbox_metrics.go
  packages/nomad/logs-collector.hcl
Labels: bug

#394 Accept out of order logs
  packages/nomad/logs-collector.hcl
Labels: bug

#395 fixed empty reader buffer after second try of calling envd init endpoint
  packages/orchestrator/internal/sandbox/envd.go
Labels: bug

#391 Periodic test for internet traffic in sandboxes
  .github/workflows/periodic-test.yml
  tests/periodic-test/internet-works.ts
Labels: improvement

#370 Deploy clickhouse on nomad
  packages/nomad/clickhouse.hcl
  packages/nomad/main.tf
Labels: feature

#389 Refactor codebase to support platform compile flags
  packages/orchestrator/cmd/mock-nbd/mock.go
  packages/orchestrator/cmd/mock-sandbox/mock.go
  packages/orchestrator/cmd/mock-snapshot/mock.go
  packages/orchestrator/internal/consul/node.go
  packages/orchestrator/internal/sandbox/fc/client_linux.go
  packages/orchestrator/internal/sandbox/fc/client_other.go
  packages/orchestrator/internal/sandbox/nbd/path_direct_linux.go
  packages/orchestrator/internal/sandbox/nbd/path_direct_other.go
  packages/orchestrator/internal/sandbox/nbd/pool.go
  packages/orchestrator/internal/sandbox/network/host_linux.go
  packages/orchestrator/internal/sandbox/network/host_other.go
  packages/orchestrator/internal/sandbox/network/network_linux.go
  packages/orchestrator/internal/sandbox/network/network_other.go
  packages/orchestrator/internal/sandbox/network/pool.go
  packages/orchestrator/internal/sandbox/network/storage.go
  packages/orchestrator/internal/sandbox/network/storage_kv.go
  packages/orchestrator/internal/sandbox/rootfs/cow.go
  packages/orchestrator/internal/sandbox/sandbox_linux.go
  packages/orchestrator/internal/sandbox/sandbox_other.go
  packages/orchestrator/internal/sandbox/uffd/handler.go
  packages/orchestrator/internal/sandbox/uffd/serve_linux.go
  packages/orchestrator/internal/sandbox/uffd/serve_other.go
  packages/orchestrator/internal/server/main.go
  packages/orchestrator/internal/server/sandboxes.go
  packages/orchestrator/internal/server/sandboxes_test.go
  packages/orchestrator/main.go
Labels: improvement

#402 clickhouse bucket prefixed with gcp project
  packages/nomad/main.tf
Labels: bug

#396 Check if the branch corresponds to the prod env
  Makefile
  scripts/confirm.sh
Labels: improvement

#404 Improve analytics reporting in the API
  packages/api/internal/cache/instance/instance.go
  packages/api/internal/cache/instance/monitoring.go
  packages/api/internal/cache/instance/operations.go
  packages/api/internal/cache/instance/sync.go
  packages/api/internal/orchestrator/analytics.go
  packages/api/internal/orchestrator/cache.go
  packages/api/internal/orchestrator/create_instance.go
  packages/api/internal/orchestrator/orchestrator.go
Labels: improvement

#407 Fixed api orchestrator timing for local dev and test
  .github/actions/start-services/action.yml
  packages/api/internal/orchestrator/orchestrator.go
Labels: bug, improvement

#403 Add orchestrator client setup to the integration tests
  .env.template
  .github/workflows/integration_tests.yml
  tests/integration/Makefile
  tests/integration/README.MD
  tests/integration/internal/setup/api_client.go
  tests/integration/internal/setup/constants.go
  tests/integration/internal/setup/orchestrator_client.go
  tests/integration/internal/tests/orchestrator/sandbox_test.go
Labels: improvement

#405 Remove unused stats handler
  packages/orchestrator/internal/sandbox/sandbox_linux.go
  packages/orchestrator/internal/sandbox/stats/stats.go
Labels: improvement

#408 Improve integration tests error when orchestrator or api fails during start
  .github/actions/start-services/action.yml
Labels: improvement

#411 Prevent removing resumed sandbox if the cleanup for the paused sandbox takes too long
  go.work.sum
  packages/api/go.mod
  packages/api/go.sum
  packages/orchestrator/internal/sandbox/sandbox_linux.go
  packages/orchestrator/internal/sandbox/sandbox_other.go
  packages/orchestrator/internal/server/sandboxes.go
Labels: bug

#413 Update comment about sandbox remove
  packages/orchestrator/internal/server/sandboxes.go
Labels: docs

#418 Fix opportunistic typo
  packages/cluster/api-cluster/main.tf
  packages/cluster/build-cluster/main.tf
  packages/cluster/client/main.tf
Labels: bug

#420 Use google.com instead of e2b.dev to test internet connectivity
  tests/periodic-test/internet-works.ts
Labels: bug

#423 Fix terraform dev environment
  packages/nomad/orchestrator.hcl
Labels: bug

#253 Automate build cache cleanup in orchestrator
  go.work.sum
  packages/orchestrator/internal/sandbox/block/cache.go
  packages/orchestrator/internal/sandbox/block/chunk.go
  packages/orchestrator/internal/sandbox/build/build.go
  packages/orchestrator/internal/sandbox/build/cache.go
  packages/orchestrator/internal/sandbox/build/cache_test.go
  packages/orchestrator/internal/sandbox/build/diff.go
  packages/orchestrator/internal/sandbox/build/local_diff.go
  packages/orchestrator/internal/sandbox/build/storage_diff.go
  packages/orchestrator/internal/sandbox/sandbox_linux.go
  packages/orchestrator/internal/sandbox/template/cache.go
  packages/orchestrator/internal/sandbox/template/storage.go
Labels: improvement

#421 Connect ClickHouse client to clickhouse deployment in terraform
  Makefile
  main.tf
  packages/api/main.tf
  packages/init/main.tf
  packages/init/outputs.tf
  packages/nomad/main.tf
  packages/nomad/variables.tf
Labels: improvement

#432 Remove unintended recursive call to prevent infinite loops
  packages/orchestrator/internal/sandbox/checks.go
Labels: bug

#419 Add rolling deployment config for clickhouse
  packages/nomad/clickhouse.hcl
  packages/nomad/main.tf
Labels: improvement

#433 Fix build cache key for snapshots
  packages/orchestrator/internal/sandbox/build/cache.go
  packages/orchestrator/internal/sandbox/build/diff.go
  packages/orchestrator/internal/sandbox/build/local_diff.go
  packages/orchestrator/internal/sandbox/build/storage_diff.go
Labels: bug

#381 Kill to handle subsequent resumes
  packages/api/internal/handlers/sandbox_kill.go
  packages/api/internal/orchestrator/orchestrator.go
  packages/orchestrator/Makefile
  packages/orchestrator/cmd/mock-sandbox/mock.go
  packages/orchestrator/cmd/mock-snapshot/mock.go
  packages/shared/pkg/db/errors.go
  packages/shared/pkg/db/snapshot.go
  tests/integration/internal/tests/api/kill_test.go
Labels: feature

#438 Fix reference to correct go file for seeding database on prep-cluster
  packages/shared/Makefile
Labels: bug

#426 Check Go deps integrity automatically
  .github/workflows/pr-go-integrity.yml
  packages/api/go.mod
  packages/api/go.sum
  packages/client-proxy/go.mod
  packages/client-proxy/go.sum
  packages/docker-reverse-proxy/go.mod
  packages/docker-reverse-proxy/go.sum
  packages/envd/go.mod
  packages/envd/go.sum
  packages/orchestrator/go.mod
  packages/orchestrator/go.sum
  packages/shared/go.mod
  packages/shared/go.sum
  packages/template-manager/go.mod
  packages/template-manager/go.sum
  scripts/golang-dependencies-integrity.sh
  tests/integration/go.mod
  tests/integration/go.sum
Labels: improvement

#444 DB Improvements - Split query
  packages/shared/pkg/db/envs.go
Labels: improvement, go

#443 Add timestamp to periodic checks
  tests/periodic-test/build-template/index.ts
  tests/periodic-test/cli-logs.ts
  tests/periodic-test/create-file.ts
  tests/periodic-test/internet-works.ts
  tests/periodic-test/run-code.ts
  tests/periodic-test/snapshot-and-resume.ts
  tests/periodic-test/utils.ts
Labels: improvement

#442 Fix ttlcache RangeBackwards data race
  go.work.sum
  packages/api/go.mod
  packages/api/go.sum
  packages/docker-reverse-proxy/go.mod
  packages/docker-reverse-proxy/go.sum
  packages/orchestrator/go.mod
  packages/orchestrator/go.sum
Labels: bug

#440 Fix gRPC idle status reporting
  packages/api/internal/orchestrator/node.go
Labels: bug

#431 Connect clickhouse client to clickhouse deployment
  main.tf
  packages/nomad/main.tf
  variables.tf
Labels: bug, improvement

#446 Refactor Supabase JWT secret handling in Nomad and API modules
  main.tf
  packages/api/outputs.tf
  packages/nomad/main.tf
  packages/nomad/variables.tf
Labels: bug

#447 Remove otel-collector target in make plan
  Makefile
Labels: bug

#449 Fix bug when template has multiple builds
  packages/shared/pkg/db/envs.go
  tests/integration/seed.go
Labels: bug

#450 run go deps sync after dependabot will create pr
  .github/workflows/pr-go-dependbot-clenaup.yml
  .github/workflows/pr-go-integrity.yml
Labels: improvement, go

#451 specify go toolchain version that should be used for build
  go.work
  packages/api/go.mod
  packages/client-proxy/go.mod
  packages/docker-reverse-proxy/go.mod
  packages/envd/go.mod
  packages/orchestrator/go.mod
  packages/shared/go.mod
  packages/template-manager/go.mod
  tests/integration/go.mod
Labels: improvement, go

#452 synced tests deps
  tests/integration/go.sum
Labels: go

#462 Add script to enable VPC flow
  packages/cluster/security/vpc-flow.sh
Labels: improvement

#436 Prevent API and Loki colocation on nodes
  packages/nomad/api.hcl
  packages/nomad/loki.hcl
  packages/nomad/main.tf
Labels: improvement

#463 Limit public access to our VM ports
  packages/cluster/network/main.tf
Labels: improvement

#467 Fix GoLint deprecations
  .golangci.yml
Labels: improvement

#465 Enable IPv6 inside of sandboxes
  packages/template-manager/internal/build/snapshot_linux.go
Labels: feature

#466 Intrusion detection system alerts
  main.tf
  packages/cluster/main.tf
  packages/cluster/security/main.tf
  packages/cluster/security/variables.tf
  packages/cluster/variables.tf
  packages/init/main.tf
  packages/init/outputs.tf
Labels: feature

#470 Allow sending data to logs collector
  packages/cluster/network/main.tf
  packages/nomad/main.tf
Labels: bug

#453 Added air live-reload on dev
  .gitignore
  packages/api/.air.toml
  packages/api/Makefile
  packages/api/main.go
Labels: improvement

#476 fixed not existing command for e2b cli auth used in api error message
  packages/api/internal/auth/middleware.go
Labels: bug

#417 Replace Nginx based session proxy with orchestrator proxy
  main.tf
  packages/client-proxy/main.go
  packages/nomad/main.tf
  packages/nomad/orchestrator.hcl
  packages/nomad/variables.tf
  packages/orchestrator/cmd/mock-sandbox/mock.go
  packages/orchestrator/cmd/mock-snapshot/mock.go
  packages/orchestrator/internal/proxy/proxy.go
  packages/orchestrator/internal/proxy/proxy_browser_502.html
  packages/orchestrator/internal/sandbox/sandbox_linux.go
  packages/orchestrator/internal/sandbox/sandbox_other.go
  packages/orchestrator/internal/server/main.go
  packages/orchestrator/internal/server/sandboxes.go
  packages/orchestrator/main.go
  packages/shared/pkg/meters/main.go
  variables.tf
Labels: improvement

#477 Fix race condition in the template manager
  packages/api/internal/handlers/template_start_build.go
  packages/api/internal/template-manager/template_manager.go
Labels: bug

#473 Improve self-host steps
  self-host.md
Labels: docs

#448 Lower Loki chunk retention and ttls
  packages/nomad/loki.hcl
Labels: bug, improvement

#478 Add logging around state transitions for TemplatesBuildCache.SetStatus
  packages/api/internal/cache/templates/cache.go
  packages/api/internal/handlers/template_start_build.go
  packages/api/internal/template-manager/template_manager.go
Labels: improvement

#482 Add more informative error message to the template manager status error
  packages/template-manager/go.mod
  packages/template-manager/internal/server/template_status.go
Labels: improvement

#415 Add basic orchestrator healthcheck
  go.work.sum
  packages/api/main.go
  packages/client-proxy/main.go
  packages/orchestrator/go.mod
  packages/orchestrator/go.sum
  packages/orchestrator/internal/server/healthcheck.go
  packages/orchestrator/internal/server/main.go
  packages/orchestrator/main.go
  packages/shared/pkg/meters/main.go
  packages/shared/pkg/telemetry/otel.go
  packages/template-manager/main.go
Labels: feature

#486 Add additional template with extra snapshot time during build
  packages/template-manager/internal/build/snapshot_linux.go
Labels: improvement

#480 Pass SDK timeout to envd command timeout
  packages/envd/internal/services/process/handler/handler.go
  packages/envd/internal/services/process/start.go
Labels: bug

#358 Test time synchronization on built templates
  .github/workflows/periodic-test.yml
  tests/periodic-test/time-is-synchronized/deno.json
  tests/periodic-test/time-is-synchronized/e2b.Dockerfile
  tests/periodic-test/time-is-synchronized/index.ts
Labels: improvement

#487 Fix periodic tests
  tests/periodic-test/time-is-synchronized/index.ts
Labels: bug

#489 Improve workflows caching
  .github/actions/build-packages/action.yml
  .github/actions/go-setup-cache/action.yml
  .github/workflows/integration_tests.yml
  .github/workflows/pr-go-dependbot-cleanup.yml
  .github/workflows/pr-go-integrity.yml
  .github/workflows/pr-tests.yml
  .github/workflows/pull-request.yml
  go.work
  packages/api/go.mod
  packages/client-proxy/go.mod
  packages/docker-reverse-proxy/go.mod
  packages/envd/go.mod
  packages/orchestrator/go.mod
  packages/shared/go.mod
  packages/template-manager/go.mod
  tests/integration/go.mod
Labels: improvement, go

#493 Wait for services healthcheck instead of sleep
  .github/actions/start-services/action.yml
  packages/orchestrator/internal/server/healthcheck.go
  scripts/start-service.sh
Labels: improvement

#494 Fix bug for outer retry will eat inner retry.stop error and continue instead of stopping bug for template manager api polling logic
  packages/api/internal/template-manager/template_manager.go
  packages/api/internal/template-manager/template_manager_test.go
Labels: bug

#491 rm unused interface
  packages/api/internal/template-manager/template_manager.go
Labels: improvement

#496 Retry integration tests on fail
  .github/workflows/integration_tests.yml
Labels: improvement

#492 Track applied migrations
  Makefile
  packages/docker-reverse-proxy/go.mod
  packages/docker-reverse-proxy/go.sum
  packages/shared/Makefile
  packages/shared/migrations/20231222181015.sql
  packages/shared/migrations/20240106121919.sql
  packages/shared/migrations/20240202120312.sql
  packages/shared/migrations/20240219190940.sql
  packages/shared/migrations/20240221023613.sql
  packages/shared/migrations/20240221215408.sql
  packages/shared/migrations/20240305221944.sql
  packages/shared/migrations/20240625095352.sql
  packages/shared/migrations/20240909142106.sql
  packages/shared/migrations/20241120222814.sql
  packages/shared/migrations/20241121225404.sql
  packages/shared/migrations/20241127174604.sql
  packages/shared/migrations/20241206124325.sql
  packages/shared/migrations/20250206105106.sql
  packages/shared/migrations/20250211160814.sql
  packages/shared/migrations/20250306105106.sql
  packages/shared/pkg/db/migrations/1_db_migrations.up.sql
  packages/shared/pkg/db/migrations/20000101000000_auth.up.sql
  packages/shared/pkg/db/migrations/20231124185944_create_schemas_and_tables.up.sql
  packages/shared/pkg/db/migrations/20231220094836_create_triggers_and_policies.up.sql
  packages/shared/pkg/db/migrations/20231222181015_add_env_resources.up.sql
  packages/shared/pkg/db/migrations/20240103104619_add_team_email.up.sql
  packages/shared/pkg/db/migrations/20240106121919_add_team_ban_fields.up.sql
  packages/shared/pkg/db/migrations/20240202120312_add_kernel_version.up.sql
  packages/shared/pkg/db/migrations/20240219190940_add_max_length_hours.up.sql
  packages/shared/pkg/db/migrations/20240221023613_add_firecracker_version.up.sql
  packages/shared/pkg/db/migrations/20240221215408_update_firecracker_version.up.sql
  packages/shared/pkg/db/migrations/20240305221944_remove_tier_resources.up.sql
  packages/shared/pkg/db/migrations/20240315165236_create_env_builds.up.sql
  packages/shared/pkg/db/migrations/20240605070918_refactor_triggers_and_policies.up.sql
  packages/shared/pkg/db/migrations/20240625095352_add_envd_version.up.sql
  packages/shared/pkg/db/migrations/20240728094137_add_default_team_flag.up.sql
  packages/shared/pkg/db/migrations/20240909142106_drop_team_policies.up.sql
  packages/shared/pkg/db/migrations/20241120222814_add_team_api_key_metadata.up.sql
  packages/shared/pkg/db/migrations/20241121225404_add_team_api_key_id.up.sql
  packages/shared/pkg/db/migrations/20241127174604_add_env_creator.up.sql
  packages/shared/pkg/db/migrations/20241206124325_add_user_team_adder.up.sql
  packages/shared/pkg/db/migrations/20241213142106_create_snapshots.up.sql
  packages/shared/pkg/db/migrations/20250106142106_remove_team_is_default.up.sql
  packages/shared/pkg/db/migrations/20250206105106_add_snapshot_constraints.up.sql
  packages/shared/pkg/db/migrations/20250211160814_add_token_hashes.up.sql
  packages/shared/pkg/db/migrations/20250306105106_add_indexes.down.sql
  packages/shared/pkg/db/migrations/20250306105106_add_indexes.up.sql
  packages/shared/pkg/db/migrator.go
  packages/shared/scripts/migrate/postgres/main.go
  tests/integration/go.mod
  tests/integration/go.sum
Labels: improvement

#485 Setup client for envd in integration tests
  .env.template
  .github/workflows/integration_tests.yml
  go.work.sum
  tests/integration/Makefile
  tests/integration/README.MD
  tests/integration/README.md
  tests/integration/go.mod
  tests/integration/go.sum
  tests/integration/internal/envd/api/client.gen.go
  tests/integration/internal/envd/api/models.gen.go
  tests/integration/internal/envd/filesystem/filesystem.pb.go
  tests/integration/internal/envd/filesystem/filesystemconnect/filesystem.connect.go
  tests/integration/internal/envd/process/process.pb.go
  tests/integration/internal/envd/process/processconnect/process.connect.go
  tests/integration/internal/setup/constants.go
  tests/integration/internal/setup/envd_client.go
  tests/integration/internal/tests/envd/filesystem_test.go
Labels: improvement

#499 Handle retry error in correct scope
  packages/api/internal/template-manager/template_manager.go
  packages/api/internal/template-manager/template_manager_test.go
Labels: bug

#475 Deploy on merge to staging
  .github/workflows/deploy-staging.yml
  .github/workflows/fc-test.yml
  Makefile
Labels: feature

#474 template manager with health endpoint and graceful shutdown
  packages/api/internal/handlers/store.go
  packages/api/internal/template-manager/client.go
  packages/api/internal/template-manager/create_template.go
  packages/api/internal/template-manager/delete_template.go
  packages/api/internal/template-manager/template_manager.go
  packages/shared/pkg/grpc/template-manager/template-manager.pb.go
  packages/shared/pkg/grpc/template-manager/template-manager_grpc.pb.go
  packages/template-manager/internal/server/create_template.go
  packages/template-manager/internal/server/delete_template.go
  packages/template-manager/internal/server/health_status.go
  packages/template-manager/internal/server/main.go
  packages/template-manager/internal/server/template_status.go
  packages/template-manager/main.go
  packages/template-manager/template-manager.proto
Labels: improvement

#503 Fix multiple requests sharing same trace ID
  packages/api/go.mod
  packages/api/internal/middleware/exclude.go
  packages/api/internal/middleware/otel/metrics/config.go
  packages/api/internal/middleware/otel/metrics/middleware.go
  packages/api/internal/middleware/otel/metrics/option.go
  packages/api/internal/middleware/otel/metrics/otelrecorder.go
  packages/api/internal/middleware/otel/metrics/recorder.go
  packages/api/internal/middleware/otel/metrics/version.go
  packages/api/internal/middleware/otel/tracing/middleware.go
  packages/api/main.go
  packages/envd/go.mod
  packages/shared/go.mod
  packages/shared/go.sum
  scripts/golang-dependencies-integrity.sh
  tests/integration/go.mod
Labels: bug

#309 Stop saving empty blocks during build
  packages/orchestrator/internal/sandbox/build/build.go
  packages/orchestrator/internal/sandbox/sandbox_linux.go
  packages/orchestrator/internal/sandbox/template/cache.go
  packages/orchestrator/internal/sandbox/template/storage.go
  packages/orchestrator/internal/sandbox/template/storage_template.go
  packages/shared/pkg/storage/gcs/object.go
  packages/shared/pkg/storage/header/diff.go
  packages/shared/pkg/storage/header/diff_test.go
  packages/shared/pkg/storage/header/mapping.go
  packages/shared/pkg/storage/template.go
  packages/template-manager/go.mod
  packages/template-manager/internal/build/build.go
Labels: improvement

#498 New kernel build script
  packages/fc-kernels/build.sh
Labels: bug

#507 Fix path in dockerfile
  packages/api/Dockerfile
Labels: bug

#506 Roll orchestrator for staging environment
  .github/actions/deploy-setup-staging/action.yml
  .github/workflows/deploy-staging.yml
  .github/workflows/deploy/deploy-staging-infra.yml
  .github/workflows/deploy/deploy-staging-jobs.yml
Labels: improvement

#509 Move actions to workflows root
  .github/workflows/deploy-staging-infra.yml
  .github/workflows/deploy-staging-jobs.yml
Labels: bug

#508 Fixed slow waiting for template build status to be fetched
  packages/api/internal/template-manager/template_manager.go
  packages/api/internal/template-manager/template_manager_test.go
Labels: bug

#510 Fix staging deploy workflows
  .github/actions/deploy-setup-staging/action.yml
  .github/workflows/deploy-staging-infra.yml
  .github/workflows/deploy-staging-jobs.yml
Labels: bug

#490 Shutdown logic for template manager
  main.tf
  packages/nomad/main.tf
  packages/nomad/template-manager.hcl
  packages/nomad/variables.tf
  packages/orchestrator/main.go
  packages/template-manager/internal/server/main.go
  packages/template-manager/main.go
Labels: improvement

#514 Add metrics for pause and resume endpoints
  packages/api/main.go
  packages/nomad/otel-collector.hcl
Labels: feature

#515 Increase staging cluster sizes to allow rolling updates
  .github/actions/deploy-setup-staging/action.yml
Labels: improvement

#518 Build and use envd for integration tests
  .github/actions/build-packages/action.yml
  .github/actions/host-init/init-client.sh
Labels: improvement

#521 Improve traces logging for cleanup
  packages/api/main.go
  packages/orchestrator/cmd/mock-nbd/mock.go
  packages/orchestrator/cmd/mock-sandbox/mock.go
  packages/orchestrator/cmd/mock-snapshot/mock.go
  packages/orchestrator/internal/sandbox/cleanup.go
  packages/orchestrator/internal/sandbox/nbd/path_direct_linux.go
  packages/orchestrator/internal/sandbox/rootfs/cow.go
  packages/orchestrator/internal/sandbox/sandbox_linux.go
  packages/orchestrator/internal/server/sandboxes.go
Labels: improvement

#472 Communicate process kill signals without being blocked by stdout/err reads
  packages/envd/debug.Dockerfile
  packages/envd/internal/services/process/handler/handler.go
  packages/envd/internal/services/process/signal.go
  packages/envd/internal/services/process/start.go
Labels: bug

#504 Return nice error html/json when sandbox isn't found
  packages/client-proxy/Dockerfile
  packages/client-proxy/html-templates/sandbox_not_found_502.html
  packages/client-proxy/main.go
  packages/orchestrator/internal/proxy/proxy.go
Labels: improvement
