Repository e2b-dev/infra, pull requests merged in 2025-05, with the labels that each got.

#604 Don't fail on remaining space eviction
  packages/orchestrator/internal/sandbox/build/cache.go
Labels: improvement

#608 Create new build id for each integrations test run
  .github/actions/build-packages/action.yml
  .github/actions/build-sandbox-template/action.yml
  .github/actions/host-init/action.yml
  packages/db/Makefile
  tests/integration/internal/main_test.go
Labels: bug

#609 Run test on main branch push
  .github/workflows/push-main.yml
Labels: improvement

#565 Report orchestrator node commit
  packages/api/internal/api/spec.gen.go
  packages/api/internal/api/types.gen.go
  packages/api/internal/orchestrator/client.go
  packages/api/internal/orchestrator/node.go
  packages/api/internal/orchestrator/orchestrator.go
  packages/orchestrator/internal/server/healthcheck.go
  packages/shared/pkg/health/main.go
  spec/openapi.yml
Labels: improvement

#613 Increase the initial huge pages ratio
  packages/cluster/scripts/start-client.sh
Labels: improvement

#619 Add index for build status
  packages/db/migrations/20250506112836_builds_status_index.sql
Labels: improvement

#621 Initialize template manager only when enabled in services
  packages/orchestrator/main.go
Labels: bug

#622 Disable stacktraces for external loggers
  packages/shared/pkg/logger/logger.go
  packages/shared/pkg/logger/sandbox/logger.go
Labels: improvement

#624 Handle slow template retrieval during sandbox start
  packages/api/internal/cache/templates/cache.go
  packages/db/queries/get_env_with_build.sql
  packages/db/queries/get_env_with_build.sql.go
Labels: bug

#616 Reconfigure timeout in envd
  packages/envd/main.go
Labels: bug, improvement

#617 Reconfigure API timeouts
  packages/api/main.go
  packages/client-proxy/internal/proxy/proxy.go
  packages/orchestrator/internal/proxy/proxy.go
  packages/shared/pkg/proxy/proxy.go
Labels: bug, improvement

#627 Use native exponential buckets for histograms
  packages/shared/pkg/telemetry/otel.go
  terraform/grafana/stack/dashboards/main/panels/sandbox-create-errors.json
  terraform/grafana/stack/dashboards/main/panels/sandbox-create-latency-long-term.json
  terraform/grafana/stack/dashboards/main/panels/sandbox-create-latency.json
  terraform/grafana/stack/dashboards/main/panels/sandbox-kill-errors.json
  terraform/grafana/stack/dashboards/main/panels/sandbox-kill-latency-long-term.json
  terraform/grafana/stack/dashboards/main/panels/sandbox-kill-latency.json
  terraform/grafana/stack/dashboards/main/panels/sandbox-pause-errors-orchestrator.json
  terraform/grafana/stack/dashboards/main/panels/sandbox-pause-errors.json
  terraform/grafana/stack/dashboards/main/panels/sandbox-pause-latency-orchestrator.json
  terraform/grafana/stack/dashboards/main/panels/sandbox-pause-latency.json
  terraform/grafana/stack/dashboards/main/panels/sandbox-resume-errors.json
  terraform/grafana/stack/dashboards/main/panels/sandbox-resume-latency.json
Labels: improvement

#631 Fix nil dereference when checking error while connecting to NDB
  packages/orchestrator/internal/sandbox/nbd/path_direct_linux.go
Labels: bug

#625 Add possibility to increase max spec via Tier table
  .github/actions/start-services/action.yml
  packages/api/internal/api/spec.gen.go
  packages/api/internal/constants/templates.go
  packages/api/internal/handlers/auth.go
  packages/api/internal/handlers/template_build_status.go
  packages/api/internal/handlers/template_delete.go
  packages/api/internal/handlers/template_request_build.go
  packages/api/internal/handlers/template_start_build.go
  packages/api/internal/handlers/template_update.go
  packages/api/internal/handlers/templates_list.go
  packages/db/migrations/20250507134356_add_max_specs_to_tier.sql
  packages/db/queries/models.go
  packages/db/queries/teams___tiers__usersteams.sql
  packages/db/queries/teams___tiers__usersteams.sql.go
  packages/shared/pkg/db/users.go
  spec/openapi.yml
  tests/integration/Makefile
  tests/integration/internal/api/client.gen.go
  tests/integration/internal/api/models.gen.go
  tests/integration/internal/setup/api_client.go
  tests/integration/internal/setup/constants.go
  tests/integration/internal/setup/envd_client.go
  tests/integration/internal/tests/api/templates/request_build_test.go
  tests/integration/internal/tests/envd/auth_test.go
  tests/integration/internal/tests/envd/signatures_test.go
  tests/integration/seed.go
Labels: improvement

#632 Use separate status for snapshots
  packages/api/internal/template-manager/template_manager.go
  packages/shared/pkg/db/snapshot.go
  packages/shared/pkg/models/envbuild/envbuild.go
  packages/shared/pkg/models/migrate/schema.go
  packages/shared/pkg/schema/build.go
Labels: bug

#626 Return early on a service error
  packages/orchestrator/main.go
Labels: improvement, go

#633 Better error for blocked teams
  packages/api/internal/auth/middleware.go
  packages/api/internal/cache/auth/cache.go
  packages/api/internal/handlers/store.go
  packages/api/internal/utils/error.go
  packages/shared/pkg/db/apiKeys.go
Labels: bug, improvement

#628 Remove proxy pool min connection enforcement
  packages/client-proxy/internal/proxy/proxy.go
  packages/orchestrator/internal/proxy/proxy.go
  packages/shared/pkg/proxy/pool/pool.go
  packages/shared/pkg/proxy/proxy.go
  packages/shared/pkg/proxy/proxy_test.go
Labels: improvement

#630 Improve comments for idle timeouts
  packages/envd/main.go
  packages/shared/pkg/proxy/proxy.go
Labels: improvement

#634 Disable `SetXForwarded` to prevent servers returning unexpected `content-location`
  packages/shared/pkg/proxy/pool/client.go
Labels: bug

#640 Remove the extra message appended to the error coming from backend
  packages/shared/pkg/proxy/pool/client.go
Labels: bug

#641 Return after port closed error handling in proxy
  packages/shared/pkg/proxy/pool/client.go
Labels: improvement

#636 Enable firewall logs for ingress
  packages/cluster/network/main.tf
Labels: improvement

#643 Fix max memory default migration
  packages/db/migrations/20250513111201_tier_fix_max_memory.sql
Labels: bug

#645 Orchestrator gRCP service info method
  Makefile
  packages/api/internal/api/spec.gen.go
  packages/api/internal/orchestrator/cache.go
  packages/api/internal/orchestrator/client.go
  packages/api/internal/template-manager/client.go
  packages/api/internal/template-manager/create_template.go
  packages/api/internal/template-manager/delete_template.go
  packages/api/internal/template-manager/template_manager.go
  packages/orchestrator/Makefile
  packages/orchestrator/info.proto
  packages/orchestrator/internal/grpcserver/healthcheck.go
  packages/orchestrator/internal/info/handlers.go
  packages/orchestrator/internal/info/store.go
  packages/orchestrator/internal/server/main.go
  packages/orchestrator/internal/server/sandboxes.go
  packages/orchestrator/internal/server/sandboxes_test.go
  packages/orchestrator/main.go
  packages/orchestrator/orchestrator.proto
  packages/orchestrator/template-manager.proto
  packages/shared/pkg/grpc/orchestrator-info/info.pb.go
  packages/shared/pkg/grpc/orchestrator-info/info_grpc.pb.go
Labels: improvement

#654 API: Request to node status will send status change to the orchestrator
  packages/api/internal/handlers/admin.go
  packages/api/internal/orchestrator/cache.go
  packages/api/internal/orchestrator/client.go
  packages/api/internal/orchestrator/node.go
Labels: improvement

#653 Use service info status to report orchestrator health check
  packages/api/internal/orchestrator/client.go
  packages/orchestrator/internal/grpcserver/healthcheck.go
  packages/orchestrator/internal/grpcserver/server.go
  packages/orchestrator/internal/healthcheck/healthcheck.go
  packages/orchestrator/internal/info/store.go
  packages/orchestrator/internal/server/main.go
  packages/orchestrator/internal/server/sandboxes_test.go
  packages/orchestrator/internal/service/info.go
  packages/orchestrator/internal/service/service.go
  packages/orchestrator/internal/service/service_info.go
  packages/orchestrator/main.go
  packages/shared/pkg/health/main.go
Labels: improvement

#657 Fix periodic tests start cmd
  tests/periodic-test/time-is-synchronized/index.ts
Labels: bug

#642 Port closed proxy test
  packages/shared/pkg/proxy/template/template.go
  tests/integration/go.mod
  tests/integration/internal/tests/envd/auth_test.go
  tests/integration/internal/tests/envd/process_test.go
  tests/integration/internal/tests/proxies/closed_port_test.go
  tests/integration/internal/utils/sandbox.go
Labels: improvement

#660 Disable staging periodic tests
  .github/workflows/periodic-test.yml
Labels: bug

#661 Disable staging periodic tests
  .github/workflows/periodic-test.yml
Labels: bug

#659 Mitigate panic in ttlcache RangeBackwards
  packages/orchestrator/internal/sandbox/build/cache.go
Labels: bug

#663 Reenable staging tests
  .github/workflows/periodic-test.yml
Labels: bug

#664 Fix start command in tests
  tests/periodic-test/time-is-synchronized/index.ts
Labels: bug

#666 Handle edge cases in service starts
  packages/orchestrator/internal/grpcserver/server.go
  packages/orchestrator/main.go
Labels: bug

#667 Fix the filter in grafana dashboard for orch cache disk
  terraform/grafana/stack/dashboards/main/panels/orchestrator-nodes-disk-cache.json
Labels: bug

#668 Fix nil pointer for old templates
  packages/orchestrator/internal/sandbox/template/storage.go
Labels: bug

#670 Nil dereference in template manager in run command
  packages/orchestrator/internal/template/build/command.go
Labels: bug

#639 Return snapshot-base template alias in list of the sandboxes
  packages/api/go.mod
  packages/api/internal/cache/instance/instance.go
  packages/api/internal/handlers/sandbox_resume.go
  packages/api/internal/handlers/sandboxes_list.go
  packages/api/internal/orchestrator/create_instance.go
  packages/api/internal/orchestrator/list_instances.go
  packages/db/queries/get_last_snapshot.sql
  packages/db/queries/get_last_snapshot.sql.go
  packages/db/queries/get_snapshots_with_cursor.sql
  packages/db/queries/get_snapshots_with_cursor.sql.go
  packages/docker-reverse-proxy/go.mod
  packages/docker-reverse-proxy/go.sum
  packages/shared/pkg/db/snapshot.go
  packages/shared/pkg/models/snapshot/snapshot_predicates.go
  tests/integration/go.mod
  tests/integration/go.sum
  tests/integration/internal/tests/api/sandbox_list_test.go
  tests/integration/internal/tests/envd/process_test.go
  tests/integration/internal/utils/sandbox.go
Labels: improvement

#672 Fix memfile header for old templates
  packages/orchestrator/internal/sandbox/template/storage.go
Labels: bug

#673 Enable TUN device
  packages/fc-kernels/configs/6.1.102.config
Labels: improvement

#674 Add info about orchestrator commit
  packages/api/internal/api/spec.gen.go
  packages/api/internal/api/types.gen.go
  packages/api/internal/orchestrator/client.go
  packages/api/internal/orchestrator/node.go
  spec/openapi.yml
Labels: improvement

#671 Orchestrators network namespaces safe-acquire
  packages/orchestrator/cmd/build-template/main.go
  packages/orchestrator/internal/sandbox/network/pool.go
  packages/orchestrator/internal/sandbox/network/storage.go
  packages/orchestrator/internal/sandbox/network/storage_kv.go
  packages/orchestrator/internal/sandbox/network/storage_local.go
  packages/orchestrator/internal/sandbox/network/storage_memory.go
  packages/orchestrator/main.go
Labels: improvement, go

#675 make the variables readonly
  packages/cluster-disk-image/setup/install-nomad.sh
  packages/cluster/scripts/run-api-nomad.sh
  packages/cluster/scripts/run-build-cluster-nomad.sh
  packages/cluster/scripts/run-nomad.sh
Labels: improvement

#677 Fix readonly variable
  packages/cluster/scripts/run-api-nomad.sh
  packages/cluster/scripts/run-build-cluster-nomad.sh
  packages/cluster/scripts/run-nomad.sh
Labels: bug

#679 Fix sandbox logs reporting for new templates
  packages/orchestrator/internal/sandbox/fc/client_linux.go
Labels: bug

#646 Remove running Docker container in template build
  go.work.sum
  packages/api/go.mod
  packages/api/go.sum
  packages/client-proxy/go.mod
  packages/client-proxy/go.sum
  packages/db/go.mod
  packages/db/go.sum
  packages/docker-reverse-proxy/go.mod
  packages/docker-reverse-proxy/go.sum
  packages/envd/go.mod
  packages/envd/go.sum
  packages/orchestrator/cmd/build-template/main.go
  packages/orchestrator/go.mod
  packages/orchestrator/go.sum
  packages/orchestrator/internal/sandbox/block/cache.go
  packages/orchestrator/internal/sandbox/block/device.go
  packages/orchestrator/internal/sandbox/block/local.go
  packages/orchestrator/internal/sandbox/block/overlay.go
  packages/orchestrator/internal/sandbox/diffcreator.go
  packages/orchestrator/internal/sandbox/fc/kernel_args.go
  packages/orchestrator/internal/sandbox/fc/process.go
  packages/orchestrator/internal/sandbox/rootfs/direct.go
  packages/orchestrator/internal/sandbox/rootfs/nbd.go
  packages/orchestrator/internal/sandbox/rootfs/rootfs.go
  packages/orchestrator/internal/sandbox/sandbox_linux.go
  packages/orchestrator/internal/sandbox/template/local_template.go
  packages/orchestrator/internal/sandbox/template/storage.go
  packages/orchestrator/internal/sandbox/template/template.go
  packages/orchestrator/internal/template/build/build.go
  packages/orchestrator/internal/template/build/configure.sh
  packages/orchestrator/internal/template/build/ext4/tools.go
  packages/orchestrator/internal/template/build/oci/oci.go
  packages/orchestrator/internal/template/build/provision.sh
  packages/orchestrator/internal/template/build/rootfs.go
  packages/orchestrator/internal/template/build/tar.go
  packages/orchestrator/internal/template/build/template_builder.go
  packages/orchestrator/internal/template/server/create_template.go
  packages/orchestrator/internal/template/server/main.go
  packages/orchestrator/internal/template/server/template_status.go
  packages/orchestrator/main.go
  packages/shared/Makefile
  packages/shared/go.mod
  packages/shared/go.sum
  packages/shared/pkg/utils/symlink.go
  tests/integration/go.mod
  tests/integration/go.sum
Labels: improvement

#680 Return a correct status code for resume conflict
  packages/api/internal/cache/instance/reservation.go
  packages/api/internal/cache/instance/reservation_test.go
  packages/api/internal/orchestrator/create_instance.go
Labels: bug

#684 Fix init path for Debian images
  packages/orchestrator/internal/template/build/rootfs.go
Labels: bug

#685 Increase envd timeout for template build
  packages/orchestrator/internal/sandbox/sandbox_linux.go
  packages/orchestrator/internal/template/build/template_builder.go
Labels: improvement

#686 Fix envd start with Docker installed
  packages/orchestrator/internal/template/build/provision.sh
  packages/orchestrator/internal/template/build/rootfs.go
Labels: bug

#687 Sync enlarge ext4 file
  packages/orchestrator/internal/template/build/ext4/tools.go
Labels: bug

#682 Update go to 1.24
  .github/actions/build-packages/action.yml
  .github/workflows/pr-tests.yml
  .golangci.yml
  go.work
  go.work.sum
  packages/api/Dockerfile
  packages/api/go.mod
  packages/api/go.sum
  packages/api/internal/cache/instance/sync.go
  packages/api/internal/handlers/store.go
  packages/client-proxy/Dockerfile
  packages/client-proxy/go.mod
  packages/db/Makefile
  packages/db/go.mod
  packages/db/go.sum
  packages/docker-reverse-proxy/Dockerfile
  packages/docker-reverse-proxy/go.mod
  packages/envd/debug.Dockerfile
  packages/envd/go.mod
  packages/envd/go.sum
  packages/envd/internal/logs/exporter/exporter.go
  packages/orchestrator/Dockerfile
  packages/orchestrator/go.mod
  packages/orchestrator/go.sum
  packages/shared/go.mod
  tests/integration/Makefile
  tests/integration/go.mod
  tests/integration/go.sum
Labels: go

#690 Delete diff files after template build
  packages/orchestrator/internal/sandbox/sandbox_linux.go
  packages/orchestrator/internal/sandbox/template/local_template.go
  packages/orchestrator/internal/sandbox/template/template.go
  packages/orchestrator/internal/template/build/template_builder.go
Labels: improvement

#689 Add execution ID
  packages/api/internal/analytics_collector/collector.pb.go
  packages/api/internal/analytics_collector/collector_grpc.pb.go
  packages/api/internal/cache/instance/instance.go
  packages/api/internal/handlers/sandbox.go
  packages/api/internal/orchestrator/cache.go
  packages/api/internal/orchestrator/create_instance.go
  packages/api/internal/orchestrator/list_instances.go
  packages/orchestrator/internal/proxy/proxy.go
  packages/orchestrator/internal/sandbox/sandbox_linux.go
  packages/orchestrator/internal/server/sandboxes.go
  packages/orchestrator/internal/template/build/template_builder.go
  packages/orchestrator/internal/template/build/template_config.go
  packages/orchestrator/orchestrator.proto
  packages/shared/pkg/grpc/orchestrator-info/info.pb.go
  packages/shared/pkg/grpc/orchestrator-info/info_grpc.pb.go
  packages/shared/pkg/grpc/orchestrator/orchestrator.pb.go
  packages/shared/pkg/grpc/orchestrator/orchestrator_grpc.pb.go
  packages/shared/pkg/grpc/template-manager/template-manager.pb.go
  packages/shared/pkg/grpc/template-manager/template-manager_grpc.pb.go
Labels: improvement

#692 Disable Juliett tests
  .github/workflows/periodic-test.yml
Labels: bug

#693 Fix dns configuration override
  packages/orchestrator/internal/template/build/provision.sh
Labels: bug

#694 Sync files explicitly before next operation
  packages/orchestrator/internal/template/build/ext4/tools.go
  packages/orchestrator/internal/template/build/memory.go
  packages/orchestrator/internal/template/build/oci/oci.go
Labels: bug

#669 Enable static check
  .golangci.yml
  packages/api/internal/auth/middleware.go
  packages/api/internal/cache/instance/instance.go
  packages/api/internal/handlers/sandbox_pause.go
  packages/api/internal/handlers/sandbox_resume.go
  packages/api/internal/handlers/sandboxes_list.go
  packages/api/internal/handlers/template_request_build.go
  packages/api/internal/handlers/template_start_build.go
  packages/api/internal/handlers/templates_list.go
  packages/api/internal/orchestrator/create_instance.go
  packages/api/internal/orchestrator/node.go
  packages/docker-reverse-proxy/internal/handlers/health.go
  packages/docker-reverse-proxy/internal/handlers/proxy.go
  packages/docker-reverse-proxy/internal/handlers/token.go
  packages/envd/internal/host/sync.go
  packages/envd/internal/services/filesystem/watch_sync.go
  packages/orchestrator/cmd/inspect-data/main.go
  packages/orchestrator/cmd/inspect-header/main.go
  packages/orchestrator/cmd/simulate-headers-merge/main.go
  packages/orchestrator/internal/sandbox/checks.go
  packages/orchestrator/internal/sandbox/diffcreator.go
  packages/orchestrator/internal/sandbox/nbd/pool.go
  packages/orchestrator/internal/sandbox/sandbox_linux.go
  packages/orchestrator/internal/sandbox/template/storage.go
  packages/orchestrator/internal/sandbox/uffd/serve_linux.go
  packages/orchestrator/internal/template/build/ext4/tools.go
  packages/orchestrator/internal/template/server/health_status.go
  packages/orchestrator/internal/template/server/template_status.go
  packages/shared/pkg/db/snapshot.go
  packages/shared/pkg/feature-flags/client_test.go
  packages/shared/pkg/logger/exporter.go
  packages/shared/pkg/logger/sandbox/logger.go
  packages/shared/pkg/logger/sandbox/sandbox_logger.go
  packages/shared/pkg/proxy/pool/client.go
  packages/shared/pkg/storage/header/diff.go
  packages/shared/pkg/storage/header/inspect.go
  packages/shared/pkg/storage/template_cache.go
  packages/shared/scripts/migrate/clickhouse/main.go
  packages/shared/scripts/migrate/postgres/main.go
  packages/shared/scripts/seed/postgres/seed-db.go
  tests/integration/seed.go
Labels: improvement

#655 Added fields to envd stat method response
  packages/envd/internal/services/filesystem/dir.go
  packages/envd/internal/services/filesystem/stat.go
  packages/envd/internal/services/filesystem/utils.go
  packages/envd/internal/services/spec/filesystem/filesystem.pb.go
  packages/envd/main.go
  packages/envd/spec/filesystem/filesystem.proto
  packages/shared/pkg/grpc/envd/filesystem/filesystem.pb.go
  tests/integration/internal/tests/envd/filesystem_test.go
Labels: improvement

#688 Use Go Tools for defining tools versions
  go.work.sum
  packages/api/Makefile
  packages/api/go.mod
  packages/api/go.sum
  packages/client-proxy/go.mod
  packages/client-proxy/go.sum
  packages/db/Makefile
  packages/db/go.mod
  packages/db/go.sum
  packages/docker-reverse-proxy/go.mod
  packages/docker-reverse-proxy/go.sum
  packages/envd/Makefile
  packages/envd/go.mod
  packages/envd/go.sum
  packages/envd/tools/tools.go
  packages/orchestrator/Makefile
  packages/orchestrator/go.mod
  packages/orchestrator/go.sum
  packages/shared/go.mod
  packages/shared/go.sum
  tests/integration/Makefile
  tests/integration/go.mod
  tests/integration/go.sum
  tests/integration/tools/tools.go
Labels: improvement, go

#698 Improve list tests - Add unique metadata per test
  tests/integration/internal/tests/api/sandbox_list_test.go
  tests/integration/internal/tests/envd/process_test.go
  tests/integration/internal/utils/sandbox.go
Labels: improvement

#705 Periodic tests Grafana alert
  .github/workflows/periodic-test.yml
Labels: feature

#709 Reenable juliett test
  .github/workflows/periodic-test.yml
Labels: bug

#710 Fix incorrect Grafana panel project name
  terraform/grafana/stack/dashboards/main/panels/build-nodes-cpu-utilization.json
Labels: bug

#711 Revert "Added fields to envd stat method response"
  packages/envd/internal/services/filesystem/dir.go
  packages/envd/internal/services/filesystem/stat.go
  packages/envd/internal/services/filesystem/utils.go
  packages/envd/internal/services/spec/filesystem/filesystem.pb.go
  packages/envd/main.go
  packages/envd/spec/filesystem/filesystem.proto
  packages/shared/pkg/grpc/envd/filesystem/filesystem.pb.go
  tests/integration/internal/tests/envd/filesystem_test.go
Labels: bug

#718 Fix nuked garyburd/redigo library
  go.work.sum
  packages/orchestrator/go.mod
  packages/orchestrator/go.sum
Labels: bug, go

#717 Improve periodic tests image url
  .github/workflows/periodic-test.yml
Labels: improvement

#720 Extend provisioning timeout to 5 minutes
  packages/orchestrator/internal/template/build/template_builder.go
Labels: improvement

#715 Support different container registry for template manager
  .github/actions/build-sandbox-template/action.yml
  .github/actions/start-services/action.yml
  go.work.sum
  packages/api/go.mod
  packages/api/go.sum
  packages/api/internal/handlers/sandbox_kill.go
  packages/api/internal/handlers/template_delete.go
  packages/api/internal/template-manager/delete_template.go
  packages/envd/go.mod
  packages/envd/go.sum
  packages/orchestrator/cmd/build-template/main.go
  packages/orchestrator/go.mod
  packages/orchestrator/go.sum
  packages/orchestrator/internal/template/build/build.go
  packages/orchestrator/internal/template/build/oci/oci.go
  packages/orchestrator/internal/template/build/rootfs.go
  packages/orchestrator/internal/template/build/template_builder.go
  packages/orchestrator/internal/template/constants/main.go
  packages/orchestrator/internal/template/server/delete_template.go
  packages/orchestrator/internal/template/server/main.go
  packages/orchestrator/internal/template/template/main.go
  packages/orchestrator/template-manager.proto
  packages/shared/go.mod
  packages/shared/go.sum
  packages/shared/pkg/artifacts-registry/registry.go
  packages/shared/pkg/artifacts-registry/registry_aws.go
  packages/shared/pkg/artifacts-registry/registry_gcp.go
  packages/shared/pkg/artifacts-registry/registry_local.go
  packages/shared/pkg/grpc/orchestrator-info/info.pb.go
  packages/shared/pkg/grpc/orchestrator-info/info_grpc.pb.go
  packages/shared/pkg/grpc/orchestrator/orchestrator.pb.go
  packages/shared/pkg/grpc/orchestrator/orchestrator_grpc.pb.go
  packages/shared/pkg/grpc/template-manager/template-manager.pb.go
  packages/shared/pkg/grpc/template-manager/template-manager_grpc.pb.go
Labels: improvement
