Repository e2b-dev/infra, pull requests merged in 2025-04, with the labels that each got.

#523 Update self-host.md to account for new jwt auth mechanism
  self-host.md
Labels: docs

#526 Fix error message in proxies
  packages/client-proxy/main.go
  packages/orchestrator/internal/proxy/proxy.go
Labels: bug

#534 Disabled keep alive on client proxy cache
  packages/client-proxy/main.go
Labels: improvement, go

#533 Fix deployment workflows
  .github/actions/deploy-setup/action.yml
  .github/workflows/build-and-upload-job.yml
  .github/workflows/deploy-infra.yml
  .github/workflows/deploy-job.yml
  Makefile
Labels: bug

#536 Add possibility to switch to managed Redis
  Makefile
  main.tf
  packages/api/internal/dns/server.go
  packages/api/internal/handlers/store.go
  packages/api/internal/orchestrator/orchestrator.go
  packages/api/main.tf
  packages/api/outputs.tf
  packages/nomad/api.hcl
  packages/nomad/main.tf
  packages/nomad/variables.tf
  terraform/redis/.terraform.lock.hcl
  terraform/redis/README.md
  terraform/redis/main.tf
  terraform/redis/variables.tf
  variables.tf
Labels: improvement

#539 Sandbox list PR Refactor
  packages/api/internal/handlers/sandboxes_list.go
  packages/api/internal/handlers/sandboxes_list_metrics.go
  packages/api/internal/utils/sandboxes_list.go
Labels: improvement

#542 Sync codebase with primary domain where cluster is running
  packages/client-proxy/main.go
  packages/orchestrator/internal/proxy/proxy.go
  spec/openapi.yml
  tests/integration/internal/setup/envd_client.go
Labels: improvement

#535 Re-added previous sandboxes list logic (v1)
  packages/api/internal/api/api.gen.go
  packages/api/internal/api/spec.gen.go
  packages/api/internal/api/types.gen.go
  packages/api/internal/handlers/sandboxes_list.go
  packages/api/internal/handlers/sandboxes_list_metrics.go
  packages/api/internal/utils/sandboxes_list.go
  spec/openapi.yml
  tests/integration/internal/api/client.gen.go
  tests/integration/internal/api/models.gen.go
  tests/integration/internal/tests/api/sandbox_list_test.go
Labels: feature, go

#525 Fix connection issue for packer build
  packages/cluster-disk-image/.terraform.lock.hcl
  packages/cluster-disk-image/Makefile
  packages/cluster-disk-image/main.pkr.hcl
  packages/cluster-disk-image/main.tf
  packages/cluster-disk-image/variables.pkr.hcl
  packages/cluster-disk-image/variables.tf
Labels: bug

#540 Remove managed Redis sharding and add replication
  terraform/redis/main.tf
Labels: improvement

#512 Use chown of chmod for user home dir to fix permission and ownership issues
  packages/template-manager/internal/build/provision.sh
  tests/integration/internal/tests/envd/filesystem_test.go
Labels: bug

#546 Stop sandboxes after each test in the integration tests
  tests/integration/internal/main_test.go
  tests/integration/internal/tests/api/sandbox_list_test.go
  tests/integration/internal/tests/api/sandbox_test.go
  tests/integration/internal/tests/envd/filesystem_test.go
  tests/integration/internal/utils/sandbox.go
Labels: improvement

#545 Redis cluster improvements
  packages/api/go.mod
  packages/api/go.sum
  packages/api/internal/dns/server.go
  packages/api/internal/handlers/store.go
  packages/api/internal/orchestrator/orchestrator.go
  packages/nomad/api.hcl
  packages/nomad/main.tf
Labels: bug

#547 Terraform fix and improve naming
  main.tf
  packages/init/main.tf
Labels: improvement

#548 Return sorting to sandbox list
  packages/api/internal/handlers/sandboxes_list.go
  tests/integration/internal/tests/api/sandbox_list_test.go
Labels: bug

#551 Fix rpc server duration filtering
  packages/nomad/otel-collector.hcl
Labels: bug

#555 Allow only plan the deployment
  .github/workflows/deploy-infra.yml
  .github/workflows/deploy-job.yml
Labels: feature

#556 Fix db seed column name
  packages/shared/scripts/seed/postgres/seed-db.go
Labels: bug

#554 Add template alias attribute to gin middleware metrics
  packages/api/internal/handlers/sandbox_create.go
  packages/api/internal/middleware/otel/metrics/middleware.go
Labels: improvement

#544 Remove nginx based session proxy completely
  main.tf
  packages/client-proxy/go.mod
  packages/client-proxy/main.go
  packages/nomad/main.tf
  packages/nomad/proxies/browser_502.html
  packages/nomad/proxies/nginx.conf
  packages/nomad/proxies/session.conf
  packages/nomad/variables.tf
  packages/orchestrator/main.go
  packages/shared/pkg/feature-flags/client-proxy/flag.go
  variables.tf
Labels: improvement

#557 Fix missing prefix + unify regexes
  terraform/grafana/stack/panels/api-nodes-cpu-utilization.json
  terraform/grafana/stack/panels/api-nodes-network-throughput.json
  terraform/grafana/stack/panels/api-nodes-ram.json
  terraform/grafana/stack/panels/orchestrator-nodes-cpu-utilization.json
  terraform/grafana/stack/panels/orchestrator-nodes-disk-cache-throughput.json
  terraform/grafana/stack/panels/orchestrator-nodes-network-throughput.json
Labels: bug, improvement

#561 Update .env.template
  .env.template
Labels: improvement

#560 Don't fail build on missing logs
  packages/api/internal/handlers/template_build_status.go
Labels: bug

#527 Envd with http auth support
  packages/envd/go.mod
  packages/envd/internal/api/api.gen.go
  packages/envd/internal/api/auth.go
  packages/envd/internal/api/auth_test.go
  packages/envd/internal/api/download.go
  packages/envd/internal/api/init.go
  packages/envd/internal/api/store.go
  packages/envd/internal/api/upload.go
  packages/envd/internal/services/spec/filesystem/filesystem.pb.go
  packages/envd/internal/services/spec/filesystem/filesystemconnect/filesystem.connect.go
  packages/envd/internal/services/spec/process/process.pb.go
  packages/envd/internal/services/spec/process/processconnect/process.connect.go
  packages/envd/main.go
  packages/envd/spec/envd.yaml
  packages/shared/pkg/keys/sha256.go
  tests/integration/internal/envd/api/client.gen.go
  tests/integration/internal/envd/api/models.gen.go
  tests/integration/internal/envd/filesystem/filesystem.pb.go
  tests/integration/internal/envd/filesystem/filesystemconnect/filesystem.connect.go
  tests/integration/internal/envd/process/process.pb.go
  tests/integration/internal/envd/process/processconnect/process.connect.go
  tests/integration/internal/setup/envd_client.go
  tests/integration/internal/tests/envd/auth_test.go
  tests/integration/internal/tests/envd/signatures_test.go
Labels: feature

#562 Fix error message type for validation
  packages/api/main.go
Labels: bug

#567 Info about team to sandbox traffic logs
  packages/client-proxy/go.mod
  packages/client-proxy/go.sum
  packages/client-proxy/main.go
  packages/orchestrator/internal/proxy/proxy.go
  packages/orchestrator/internal/sandbox/sandbox_linux.go
Labels: improvement

#524 Add optional depth parameter to envd's ListDir
  packages/envd/Makefile
  packages/envd/internal/services/filesystem/dir.go
  packages/envd/internal/services/spec/filesystem/filesystem.pb.go
  packages/envd/main.go
  packages/envd/spec/filesystem/filesystem.proto
  tests/integration/README.md
  tests/integration/internal/envd/filesystem/filesystem.pb.go
  tests/integration/internal/tests/envd/filesystem_test.go
Labels: feature

#247 Increase memory during build when memory for the template is small
  packages/template-manager/internal/build/rootfs.go
Labels: bug

#573 Fix integration tests
  packages/envd/internal/services/filesystem/dir.go
  packages/envd/internal/services/filesystem/move.go
  packages/envd/internal/services/filesystem/stat.go
  packages/envd/internal/services/filesystem/utils.go
  tests/integration/internal/tests/envd/filesystem_test.go
Labels: bug

#574 Fix missing property in filessystem stat
  packages/envd/internal/services/filesystem/stat.go
Labels: bug

#572 Add more info to the unknown envd errors
  packages/envd/internal/services/filesystem/watch.go
  packages/envd/internal/services/process/connect.go
  packages/envd/internal/services/process/input.go
  packages/envd/internal/services/process/start.go
Labels: improvement

#577 Avoid panic in list test
  tests/integration/internal/tests/api/kill_test.go
  tests/integration/internal/tests/api/sandbox_list_test.go
  tests/integration/internal/tests/envd/auth_test.go
Labels: improvement

#580 Add sandbox ID info to periodic test
  tests/periodic-test/cli-logs.ts
  tests/periodic-test/create-file.ts
  tests/periodic-test/internet-works.ts
  tests/periodic-test/run-code.ts
  tests/periodic-test/snapshot-and-resume.ts
  tests/periodic-test/time-is-synchronized/index.ts
Labels: improvement

#581 Fix race conditon between process cancellation and pipe closing
  packages/envd/internal/services/process/handler/handler.go
  packages/envd/internal/services/process/start.go
Labels: bug, improvement

#582 Fix flaky tests reporting
  .github/workflows/pull-request.yml
  tests/integration/internal/tests/api/kill_test.go
  tests/integration/internal/tests/envd/auth_test.go
Labels: bug

#570 Improve graph for pause error traces
  terraform/grafana/stack/panels/sandbox-pause-errors-old.json
  terraform/grafana/stack/panels/sandbox-pause-latency-old.json
Labels: improvement

#585 Improve lifecycle cache unit test flakiness
  packages/api/internal/cache/instance/lifecycle_cache_test.go
Labels: improvement

#587 Print envd logs on integration test envd init fail
  tests/integration/internal/setup/envd_client.go
  tests/integration/internal/tests/envd/auth_test.go
Labels: bug, improvement

#589 Use goose for migrations
  Makefile
  packages/db/Makefile
  packages/db/go.mod
  packages/db/go.sum
  packages/db/migrations/1_db_migrations.up.sql
  packages/db/migrations/20000101000000_auth.sql
  packages/db/migrations/20000101000001_rls_for_migration_table.sql
  packages/db/migrations/20231124185944_create_schemas_and_tables.sql
  packages/db/migrations/20231220094836_create_triggers_and_policies.sql
  packages/db/migrations/20231222181015_add_env_resources.sql
  packages/db/migrations/20240103104619_add_team_email.sql
  packages/db/migrations/20240106121919_add_team_ban_fields.sql
  packages/db/migrations/20240202120312_add_kernel_version.sql
  packages/db/migrations/20240219190940_add_max_length_hours.sql
  packages/db/migrations/20240221023613_add_firecracker_version.sql
  packages/db/migrations/20240221215408_update_firecracker_version.sql
  packages/db/migrations/20240221215408_update_firecracker_version.up.sql
  packages/db/migrations/20240305221944_remove_tier_resources.sql
  packages/db/migrations/20240315165236_create_env_builds.sql
  packages/db/migrations/20240605070918_refactor_triggers_and_policies.sql
  packages/db/migrations/20240625095352_add_envd_version.sql
  packages/db/migrations/20240728094137_add_default_team_flag.sql
  packages/db/migrations/20240909142106_drop_team_policies.sql
  packages/db/migrations/20241120222814_add_team_api_key_metadata.sql
  packages/db/migrations/20241121225404_add_team_api_key_id.sql
  packages/db/migrations/20241127174604_add_env_creator.sql
  packages/db/migrations/20241206124325_add_user_team_adder.sql
  packages/db/migrations/20241213142106_create_snapshots.sql
  packages/db/migrations/20250106142106_remove_team_is_default.sql
  packages/db/migrations/20250206105106_add_snapshot_constraints.sql
  packages/db/migrations/20250211160814_add_token_hashes.sql
  packages/db/migrations/20250306105106_add_indexes.down.sql
  packages/db/migrations/20250306105106_add_indexes.sql
  packages/db/migrations/20250404151700_add_snapshots_sbx_started_at.sql
  packages/db/migrator/migrator.go
  packages/db/queries/models.go
  packages/db/scripts/migrate/postgres/main.go
Labels: improvement, go

#592 Fix missing "goose" during deployment when running `make migrate`
  .github/workflows/deploy-infra.yml
Labels: bug

#517 Improve NBD handling
  packages/orchestrator/internal/sandbox/nbd/dispatch.go
  packages/orchestrator/internal/sandbox/nbd/path_direct_linux.go
  packages/orchestrator/internal/sandbox/nbd/pool.go
  packages/orchestrator/internal/sandbox/rootfs/cow.go
  packages/orchestrator/internal/sandbox/sandbox_linux.go
Labels: bug, improvement

#591 Add check for out of order migrations
  .github/workflows/out-of-order-migrations.yml
  .github/workflows/pull-request.yml
Labels: improvement

#593 Improve periodic tests command output streaming
  tests/periodic-test/time-is-synchronized/index.ts
Labels: improvement

#597 Improve periodic tests error catch
  tests/periodic-test/time-is-synchronized/index.ts
Labels: improvement

#594 Add kill process test
  packages/template-manager/cmd/build-template/main.go
  tests/integration/internal/setup/constants.go
  tests/integration/internal/setup/envd_client.go
  tests/integration/internal/tests/envd/process_test.go
  tests/integration/internal/utils/sandbox.go
Labels: feature

#599 Rethrow periodic test error
  tests/periodic-test/time-is-synchronized/index.ts
Labels: bug

#600 Fix last build query
  packages/db/Makefile
  packages/db/queries/db.go
  packages/db/queries/get_env_with_build.sql
  packages/db/queries/get_env_with_build.sql.go
  packages/db/queries/get_last_snapshot.sql.go
  packages/db/queries/models.go
  packages/db/queries/teams_usersteams_join.sql.go
Labels: bug

#601 Increase start command wait time
  packages/template-manager/internal/build/snapshot_linux.go
Labels: bug

#598 Improve template manager logs
  packages/nomad/logs-collector.hcl
  packages/template-manager/cmd/build-template/main.go
  packages/template-manager/internal/build/build.go
  packages/template-manager/internal/build/network_linux.go
  packages/template-manager/internal/build/network_other.go
  packages/template-manager/internal/build/provision.sh
  packages/template-manager/internal/build/rootfs.go
  packages/template-manager/internal/build/snapshot_linux.go
  packages/template-manager/internal/build/template.go
  packages/template-manager/internal/build/writer/postprocessor.go
  packages/template-manager/internal/build/writer/postprocessor_test.go
  packages/template-manager/internal/test/build.go
Labels: improvement
